import { basicScene, ground, box, sphere, cylinder, material, createTree, createBuilding, seeded, label } from '../../core/scene.js';
const $=(r,s)=>r.querySelector(s);const $$=(r,s)=>[...r.querySelectorAll(s)];const wait=ms=>new Promise(r=>setTimeout(r,ms));
function domController(stage,reset,cleanup,engine){return{dispose(){cleanup?.();stage.replaceChildren();},reset,getStats(){return{engine,fps:'DOM',scene:`${stage.querySelectorAll('button').length} controls`};}};}

export function createAccessibilityLab({stage,toast}){
  const issues={contrast:false,label:false,heading:false,focus:false,motion:false};
  stage.innerHTML=`<section class="a11y-tool"><header><div><span>WCAG 2.2 INTERACTIVE LAB</span><strong>Accessibility Testing Lab</strong></div><div class="a11y-score"><b data-a11y-score>100</b><span>/100</span></div></header><div class="a11y-layout"><aside><h3>INJECT ISSUES</h3>${[['contrast','Low contrast'],['label','Missing form label'],['heading','Broken heading order'],['focus','Hidden focus'],['motion','Forced animation']].map(x=>`<label><input type="checkbox" data-issue="${x[0]}"><span>${x[1]}</span></label>`).join('')}<button data-keyboard>Start keyboard test</button><div data-focus-path>Focus path: not started</div></aside><main><div class="device-browser"><div class="browser-chrome"><i></i><i></i><i></i><span>example-product.test</span></div><div class="a11y-preview" data-preview><header><a href="#">Northstar</a><nav><a href="#">Features</a><a href="#">Pricing</a></nav></header><main><h1>Ship a better product.</h1><p>One accessible workspace for planning, building, and support.</p><form><label data-form-label>Email address<input type="email" placeholder="you@example.com"></label><button>Start free</button></form><h2 data-subheading>Trusted by practical teams</h2><div class="preview-cards"><article>Fast setup</article><article>Clear reporting</article><article>Real support</article></div></main></div></div></main><aside class="a11y-inspector"><h3>ACCESSIBILITY TREE</h3><ol data-tree><li>banner</li><li>navigation</li><li>main</li><li>heading level 1</li><li>form</li><li>heading level 2</li></ol><h3>FINDINGS</h3><div data-findings><p>No injected failures.</p></div></aside></div></section>`;
  function render(){const active=Object.entries(issues).filter(x=>x[1]).map(x=>x[0]),score=100-active.length*16;$(stage,'[data-a11y-score]').textContent=score;const preview=$(stage,'[data-preview]');preview.className=`a11y-preview ${active.map(x=>'issue-'+x).join(' ')}`;const label=$(stage,'[data-form-label]');if(issues.label){label.childNodes[0].textContent='';label.setAttribute('aria-label','');}else label.childNodes[0].textContent='Email address';$(stage,'[data-subheading]').outerHTML=issues.heading?'<h4 data-subheading>Trusted by practical teams</h4>':'<h2 data-subheading>Trusted by practical teams</h2>';$(stage,'[data-tree]').innerHTML=`<li>banner</li><li>navigation</li><li>main</li><li>heading level 1</li><li>form${issues.label?' · unnamed input':''}</li><li>heading level ${issues.heading?'4 ⚠':'2'}</li>`;$(stage,'[data-findings]').innerHTML=active.length?active.map(x=>`<article><b>FAIL</b><strong>${{contrast:'Text contrast is 2.1:1',label:'Input has no accessible name',heading:'Heading jumps from H1 to H4',focus:'Keyboard focus is invisible',motion:'Animation ignores reduced motion'}[x]}</strong><p>${{contrast:'WCAG 1.4.3 requires at least 4.5:1 for normal text.',label:'WCAG 1.3.1 and 4.1.2 require a programmatic name.',heading:'Use a logical heading outline.',focus:'WCAG 2.4.7 requires visible focus.',motion:'WCAG 2.3.3 requires motion controls.'}[x]}</p></article>`).join(''):'<p>No injected failures.</p>';}
  $$ (stage,'[data-issue]').forEach(i=>i.addEventListener('change',()=>{issues[i.dataset.issue]=i.checked;render();}));$(stage,'[data-keyboard]').addEventListener('click',async()=>{const path=['Logo link','Features link','Pricing link','Email input','Start free button'];for(const item of path){$(stage,'[data-focus-path]').textContent=`Focus path: ${item}`;await wait(450);}toast('Keyboard path completed');});render();return domController(stage,()=>{$$ (stage,'[data-issue]').forEach(i=>i.checked=false);Object.keys(issues).forEach(k=>issues[k]=false);render();},null,'ACCESSIBILITY INSPECTOR');
}
