import { basicScene, ground, box, sphere, cylinder, material, createTree, createBuilding, seeded, label } from '../../core/scene.js';
const $=(r,s)=>r.querySelector(s);const $$=(r,s)=>[...r.querySelectorAll(s)];const wait=ms=>new Promise(r=>setTimeout(r,ms));
function domController(stage,reset,cleanup,engine){return{dispose(){cleanup?.();stage.replaceChildren();},reset,getStats(){return{engine,fps:'DOM',scene:`${stage.querySelectorAll('button').length} controls`};}};}

const services={cdn:{name:'CloudFront',icon:'◎',color:'#0ea5e9',cost:4,lat:-42,rel:2},api:{name:'API Gateway',icon:'⇄',color:'#8b5cf6',cost:6,lat:18,rel:1},lambda:{name:'Lambda',icon:'λ',color:'#f97316',cost:5,lat:30,rel:1},db:{name:'DynamoDB',icon:'▤',color:'#10b981',cost:12,lat:20,rel:4},queue:{name:'SQS Queue',icon:'≡',color:'#f59e0b',cost:4,lat:50,rel:6},cache:{name:'Redis Cache',icon:'⚡',color:'#ef4444',cost:7,lat:-55,rel:2},monitor:{name:'Observability',icon:'◉',color:'#2563eb',cost:3,lat:0,rel:5}};
export function createArchitectureBuilder({stage,toast}){
  stage.innerHTML=`<section class="tool-shell architecture-tool" style="--tool-bg:#eef4fb;--tool-text:#12233c;--tool-line:#cbd8e8;--tool-accent:#2563eb"><header class="tool-header"><div><h2>Cloud Architecture Builder</h2><p>Design a request path and test its behavior.</p></div><div class="tool-actions"><button data-arch="simulate" class="primary">Simulate request</button><button data-arch="clear">Clear</button><button data-arch="export">Export</button></div></header><div class="architecture-layout"><aside class="service-palette"><strong>SERVICES</strong>${Object.entries(services).map(([id,s])=>`<button data-service="${id}" style="--service:${s.color}"><i>${s.icon}</i><span><b>${s.name}</b><small>$${s.cost}/mo</small></span></button>`).join('')}</aside><main class="architecture-board" data-board><svg data-links></svg><div class="board-grid"></div><p data-empty>Add services from the left, drag them, then connect them from the inspector.</p><i class="request-packet" data-packet></i></main><aside class="architecture-inspector"><strong>INSPECTOR</strong><div data-inspector><p>Select a node.</p></div><div class="architecture-metrics"><span>Cost <b data-cost>$0</b></span><span>Latency <b data-latency>140ms</b></span><span>Reliability <b data-reliability>88%</b></span><span>Request <b data-request>Not run</b></span></div><p data-advice>Add observability and failure isolation before production.</p></aside></div></section>`;
  const board=$(stage,'[data-board]'),svg=$(stage,'[data-links]'),packet=$(stage,'[data-packet]');let nodes=[],links=[],selected=null,id=0;
  function metrics(){const cost=nodes.reduce((a,n)=>a+n.s.cost,0),lat=Math.max(20,140+nodes.reduce((a,n)=>a+n.s.lat,0)),rel=Math.min(99.99,88+nodes.reduce((a,n)=>a+n.s.rel,0));$(stage,'[data-cost]').textContent=`$${cost}/mo`;$(stage,'[data-latency]').textContent=`${lat}ms`;$(stage,'[data-reliability]').textContent=`${rel.toFixed(2)}%`;$(stage,'[data-advice]').textContent=!nodes.some(n=>n.type==='monitor')?'Add observability before production.':!nodes.some(n=>n.type==='queue')?'A queue would isolate downstream failures.':'Architecture includes monitoring and failure isolation.';$(stage,'[data-empty]').hidden=nodes.length>0;}
  function draw(){svg.innerHTML=links.map(([a,b])=>{const n1=nodes.find(n=>n.id===a),n2=nodes.find(n=>n.id===b);if(!n1||!n2)return'';return`<path d="M${n1.x+65} ${n1.y+35} C${n1.x+135} ${n1.y+35},${n2.x-70} ${n2.y+35},${n2.x} ${n2.y+35}"/>`;}).join('');}
  function inspector(){const wrap=$(stage,'[data-inspector]');const n=nodes.find(n=>n.id===selected);if(!n){wrap.innerHTML='<p>Select a node.</p>';return;}wrap.innerHTML=`<div class="inspected-service" style="--service:${n.s.color}"><i>${n.s.icon}</i><span><b>${n.label}</b><small>${n.type}</small></span></div><label>Label<input data-label value="${n.label}"></label><label>Connect to<select data-connect><option value="">Choose node</option>${nodes.filter(x=>x.id!==n.id).map(x=>`<option value="${x.id}">${x.label}</option>`).join('')}</select></label><button data-connect-button>Connect</button><button data-delete>Delete</button>`;$(wrap,'[data-label]').addEventListener('input',e=>{n.label=e.target.value;n.el.querySelector('b').textContent=n.label;});$(wrap,'[data-connect-button]').addEventListener('click',()=>{const target=Number($(wrap,'[data-connect]').value);if(target&&!links.some(l=>l[0]===n.id&&l[1]===target)){links.push([n.id,target]);draw();}});$(wrap,'[data-delete]').addEventListener('click',()=>{n.el.remove();nodes=nodes.filter(x=>x!==n);links=links.filter(l=>!l.includes(n.id));selected=null;draw();metrics();inspector();});}
  function add(type){const s=services[type],nodeId=++id,x=80+(nodes.length%3)*180,y=70+Math.floor(nodes.length/3)*130,el=document.createElement('button');el.className='architecture-node';el.style.cssText=`--service:${s.color};transform:translate(${x}px,${y}px)`;el.innerHTML=`<i>${s.icon}</i><span><b>${s.name}</b><small>${type}</small></span><em>⋮⋮</em>`;board.append(el);const n={id:nodeId,type,s,label:s.name,x,y,el};nodes.push(n);let drag=false,dx=0,dy=0;el.addEventListener('pointerdown',e=>{selected=nodeId;$$ (stage,'.architecture-node').forEach(x=>x.classList.toggle('selected',x===el));inspector();if(e.target.closest('em')){drag=true;dx=e.clientX-n.x;dy=e.clientY-n.y;el.setPointerCapture(e.pointerId);}});el.addEventListener('pointermove',e=>{if(!drag)return;const r=board.getBoundingClientRect();n.x=Math.max(0,Math.min(r.width-140,e.clientX-r.left-dx));n.y=Math.max(0,Math.min(r.height-80,e.clientY-r.top-dy));el.style.transform=`translate(${n.x}px,${n.y}px)`;draw();});el.addEventListener('pointerup',()=>drag=false);metrics();}
  $$ (stage,'[data-service]').forEach(b=>b.addEventListener('click',()=>add(b.dataset.service)));$(stage,'[data-arch="clear"]').addEventListener('click',()=>{nodes.forEach(n=>n.el.remove());nodes=[];links=[];selected=null;draw();metrics();inspector();});$(stage,'[data-arch="simulate"]').addEventListener('click',async()=>{if(!nodes.length)return toast('Add at least one service');$(stage,'[data-request]').textContent='Running';for(const n of nodes){packet.style.transform=`translate(${n.x+55}px,${n.y+27}px)`;n.el.classList.add('request-active');await wait(430);n.el.classList.remove('request-active');}$(stage,'[data-request]').textContent=nodes.some(n=>n.type==='monitor')?'200 OK · observed':'200 OK · blind';});$(stage,'[data-arch="export"]').addEventListener('click',()=>{navigator.clipboard?.writeText(JSON.stringify({nodes:nodes.map(({id,type,label,x,y})=>({id,type,label,x,y})),links},null,2));toast('Architecture JSON copied');});metrics();return domController(stage,()=>$(stage,'[data-arch="clear"]').click(),null,'CLOUD GRAPH EDITOR');
}
