import { basicScene, ground, box, sphere, cylinder, material, createTree, createBuilding, seeded, label } from '../../core/scene.js';
const $=(r,s)=>r.querySelector(s);const $$=(r,s)=>[...r.querySelectorAll(s)];const wait=ms=>new Promise(r=>setTimeout(r,ms));
function domController(stage,reset,cleanup,engine){return{dispose(){cleanup?.();stage.replaceChildren();},reset,getStats(){return{engine,fps:'DOM',scene:`${stage.querySelectorAll('button').length} controls`};}};}

function analyzeSeo(text){const has=re=>re.test(text),checks=[['Title tag',has(/<title>[^<]{20,65}<\/title>/i),18,'Write one descriptive 20–65 character title.'],['Meta description',has(/name=["']description["'][^>]+content=["'][^"']{70,170}/i),16,'Add a benefit-led 70–170 character description.'],['Single H1',(text.match(/<h1\b/gi)||[]).length===1,14,'Use one clear primary H1.'],['Direct answer',has(/\b(what|how|why|who|when|where)\b/i)&&has(/<p>/i),14,'Answer a concrete user question directly.'],['Entity clarity',has(/Brad|AWS|Matera|ProjectHub/i),12,'Name entities consistently.'],['Internal link',has(/<a\b[^>]+href=["']\//i),10,'Provide a meaningful internal next action.'],['Structured data',has(/ld\+json|schema\.org/i),10,'Add relevant JSON-LD.'],['Heading structure',has(/<h2\b/i),6,'Use descriptive H2 sections.']];return{checks,score:checks.reduce((a,c)=>a+(c[1]?c[2]:0),0)};}
export function createSeoAuditor({stage,toast}){
  const sample=`<!doctype html>\n<html><head><title>Brad Matera Cloud and Frontend Engineering Portfolio</title><meta name="description" content="Explore Brad Matera's AWS cloud support, frontend engineering, interactive systems, and grounded agent projects with verified evidence."></head><body><h1>Cloud and frontend engineering</h1><p>What cloud support experience does Brad have? Brad completed a 12-week AWS Cloud Support Associate internship.</p><h2>Verified projects</h2><a href="/projects">Review projects</a><script type="application/ld+json">{}</script></body></html>`;
  stage.innerHTML=`<section class="seo-tool"><header><div><span>TECHNICAL + ANSWER ENGINE</span><strong>SEO / AEO Auditor</strong></div><button data-seo="sample">Load sample</button><button data-seo="run">Run full audit</button></header><div class="seo-editor"><label>PAGE SOURCE<textarea data-seo-source spellcheck="false"><html><head><title>Home</title></head><body><h1>Welcome</h1><p>We make websites.</p></body></html></textarea></label><aside><div class="seo-score"><svg viewBox="0 0 120 120"><circle cx="60" cy="60" r="48"/><circle data-score-ring cx="60" cy="60" r="48"/></svg><strong data-seo-score>--</strong><span>OVERALL</span></div><div class="search-preview"><small>SEARCH PREVIEW</small><b data-preview-title>Home</b><a>bradleymatera.dev</a><p data-preview-copy>No meta description found.</p></div></aside></div><div class="seo-results" data-seo-results><p>Run an audit to generate prioritized findings.</p></div></section>`;
  function audit(){const text=$(stage,'[data-seo-source]').value,{checks,score}=analyzeSeo(text);$(stage,'[data-seo-score]').textContent=score;$(stage,'[data-score-ring]').style.strokeDashoffset=302-(302*score/100);$(stage,'[data-preview-title]').textContent=text.match(/<title>([^<]*)/i)?.[1]||'Missing title';$(stage,'[data-preview-copy]').textContent=text.match(/name=["']description["'][^>]+content=["']([^"']*)/i)?.[1]||'No meta description found.';$(stage,'[data-seo-results]').innerHTML=checks.sort((a,b)=>Number(a[1])-Number(b[1])).map((c,i)=>`<article class="${c[1]?'pass':'fail'}"><i>${c[1]?'✓':'!'}</i><div><span>${c[1]?'PASS':'PRIORITY '+(i+1)}</span><strong>${c[0]}</strong><p>${c[3]}</p></div><b>${c[2]} pts</b></article>`).join('');toast(`Audit complete: ${score}/100`);}
  $(stage,'[data-seo="sample"]').addEventListener('click',()=>{$(stage,'[data-seo-source]').value=sample;audit();});$(stage,'[data-seo="run"]').addEventListener('click',audit);return domController(stage,()=>{$(stage,'[data-seo-source]').value='<html><head><title>Home</title></head><body><h1>Welcome</h1><p>We make websites.</p></body></html>';$(stage,'[data-seo-results]').innerHTML='<p>Run an audit to generate prioritized findings.</p>';$(stage,'[data-seo-score]').textContent='--';},null,'SEO / AEO ANALYZER');
}
