import { basicScene, ground, box, sphere, cylinder, material, createTree, createBuilding, seeded, label } from '../../core/scene.js';
const $=(r,s)=>r.querySelector(s);const $$=(r,s)=>[...r.querySelectorAll(s)];const wait=ms=>new Promise(r=>setTimeout(r,ms));
function domController(stage,reset,cleanup,engine){return{dispose(){cleanup?.();stage.replaceChildren();},reset,getStats(){return{engine,fps:'DOM',scene:`${stage.querySelectorAll('button').length} controls`};}};}

export async function createShaderLab({stage,toast}){
  stage.innerHTML=`<section class="shader-tool"><aside><span>MATERIAL CONTROLS</span><label>Model<select data-model><option value="sphere">Sphere</option><option value="torus">Torus knot</option><option value="helmet">Procedural helmet</option></select></label><label>Base color<input type="color" data-color value="#8b5cf6"></label><label>Metallic <output data-metal-out>70%</output><input type="range" data-metal min="0" max="100" value="70"></label><label>Roughness <output data-rough-out>24%</output><input type="range" data-rough min="0" max="100" value="24"></label><label>Glow <output data-glow-out>35%</output><input type="range" data-glow min="0" max="100" value="35"></label><button data-preset>Load neon glass preset</button></aside><main><canvas aria-label="Babylon.js material preview"></canvas><div class="shader-stats"><span>LIVE PBR</span><strong data-shader-name>Violet alloy</strong></div></main><aside class="shader-code"><span>FRAGMENT IDEA</span><textarea spellcheck="false" data-code>baseColor = violet;
metallic = 0.70;
roughness = 0.24;
emissive = 0.35;</textarea><button data-compile>Apply values</button><pre data-compile-log>Material compiled successfully.</pre></aside></section>`;
  const canvas=$(stage,'canvas'),ctx=basicScene(canvas,{clear:'#080510ff',radius:8,target:[0,0.4,0],bloomWeight:.35,glow:.9});const {scene,BABYLON}=ctx;ground(scene,{width:16,height:12,color:'#0e0a18'});let mesh;const mat=material(scene,'previewMaterial','#8b5cf6',{metallic:.7,roughness:.24,emissive:'#8b5cf6',emissiveIntensity:.35});
  function model(type){mesh?.dispose();if(type==='sphere')mesh=BABYLON.MeshBuilder.CreateSphere('previewSphere',{diameter:3.6,segments:64},scene);else if(type==='torus')mesh=BABYLON.MeshBuilder.CreateTorusKnot('previewTorus',{radius:1.45,tube:.48,radialSegments:128,tubularSegments:32,p:2,q:3},scene);else{const root=new BABYLON.TransformNode('helmetRoot',scene),shell=BABYLON.MeshBuilder.CreateSphere('helmetShell',{diameter:3.5,segments:48,slice:.72},scene);shell.scaling.y=1.12;shell.parent=root;const visor=box(scene,'helmetVisor',[2.6,.9,.18],[0,.25,-1.52],'#0c1827',{metallic:.8,roughness:.1,emissive:'#38bdf8',emissiveIntensity:.55});visor.parent=root;mesh=root;}mesh.material=mat;mesh.position.y=2;mesh.getChildMeshes?.().forEach(m=>{if(m.name==='helmetShell')m.material=mat;});}
  model('sphere');scene.onBeforeRenderObservable.add(()=>{if(mesh)mesh.rotation.y+=.005;});
  function apply(){const hex=$(stage,'[data-color]').value,metal=Number($(stage,'[data-metal]').value)/100,rough=Number($(stage,'[data-rough]').value)/100,glow=Number($(stage,'[data-glow]').value)/100;mat.albedoColor=BABYLON.Color3.FromHexString(hex);mat.emissiveColor=BABYLON.Color3.FromHexString(hex);mat.emissiveIntensity=glow;mat.metallic=metal;mat.roughness=rough;$(stage,'[data-metal-out]').textContent=`${Math.round(metal*100)}%`;$(stage,'[data-rough-out]').textContent=`${Math.round(rough*100)}%`;$(stage,'[data-glow-out]').textContent=`${Math.round(glow*100)}%`;$(stage,'[data-shader-name]').textContent=`${hex} · PBR`;$(stage,'[data-code]').value=`baseColor = ${hex};\nmetallic = ${metal.toFixed(2)};\nroughness = ${rough.toFixed(2)};\nemissive = ${glow.toFixed(2)};`;}
  $$ (stage,'[data-color],[data-metal],[data-rough],[data-glow]').forEach(i=>i.addEventListener('input',apply));$(stage,'[data-model]').addEventListener('change',e=>model(e.target.value));$(stage,'[data-preset]').addEventListener('click',()=>{$(stage,'[data-color]').value='#22d3ee';$(stage,'[data-metal]').value=35;$(stage,'[data-rough]').value=8;$(stage,'[data-glow]').value=82;apply();toast('Neon glass preset applied');});$(stage,'[data-compile]').addEventListener('click',()=>{$(stage,'[data-compile-log]').textContent='Values parsed and material updated.';apply();});return{dispose(){ctx.dispose();},reset(){model('sphere');$(stage,'[data-color]').value='#8b5cf6';$(stage,'[data-metal]').value=70;$(stage,'[data-rough]').value=24;$(stage,'[data-glow]').value=35;apply();},getStats(){return ctx.stats('BABYLON.JS PBR LAB');}};
}
