const $=(r,s)=>r.querySelector(s);const $$=(r,s)=>[...r.querySelectorAll(s)];
function controller(stage,reset,engine='RESPONSIVE WEBSITE'){return{dispose(){stage.replaceChildren();},reset,getStats(){return{engine,fps:'DOM',scene:`${stage.querySelectorAll('img').length} original images · ${stage.querySelectorAll('button').length} controls`};}};}
function wirePages(stage, render, initial='home'){
  let current=initial;
  const show=(page)=>{current=page;render(page);$$ (stage,'[data-page]').forEach(b=>b.classList.toggle('active',b.dataset.page===page));stage.querySelector('.website-frame')?.scrollTo({top:0,behavior:'smooth'});};
  stage.addEventListener('click',e=>{const target=e.target.closest('[data-page]');if(target)show(target.dataset.page);});
  show(initial);return()=>show(initial);
}


export function createFairwayStore({stage,toast}){
  const products=[{name:'Tour Putter',category:'Clubs',price:229,color:'#dfe6e9'},{name:'Players Towel',category:'Accessories',price:34,color:'#143d2a'},{name:'Sunday Carry Bag',category:'Bags',price:179,color:'#d4a94f'},{name:'Alignment Marker',category:'Accessories',price:19,color:'#e85d4a'},{name:'Forged Wedge',category:'Clubs',price:149,color:'#cbd5e1'},{name:'Rope Golf Hat',category:'Apparel',price:32,color:'#f2efe7'}];
  stage.innerHTML=`<div class="website-frame fairway-site" style="--site-bg:#f5f0df;--site-text:#14261c;--site-muted:#5d6d62;--site-accent:#2f6d44;--site-cta-text:#fff;--site-font:Georgia,serif"><nav class="site-nav"><strong class="site-logo">BRADLEY’S FAIRWAY</strong><button data-page="home">Home</button><button data-page="shop">Shop</button><button data-page="journal">Journal</button><button data-page="about">Our story</button><button class="site-cta" data-cart>Bag <b data-cart-count>0</b></button></nav><main data-site-content></main><aside class="store-cart" data-cart-drawer hidden><header><strong>Your golf bag</strong><button data-cart-close>×</button></header><div data-cart-items><p>Your bag is empty.</p></div><footer><span>Total</span><strong data-cart-total>$0</strong><button>Continue to checkout</button></footer></aside></div>`;
  let cart=[];function productCard(p,i){return`<article class="product-card"><div class="product-art" style="--product:${p.color}"><span>${p.category==='Clubs'?'⛳':p.category==='Bags'?'BAG':'BF'}</span></div><small>${p.category}</small><h4>${p.name}</h4><div><strong>$${p.price}</strong><button data-add="${i}">Quick add</button></div></article>`;}
  const render=page=>{const c=$(stage,'[data-site-content]');if(page==='home')c.innerHTML=`<section class="site-hero fairway-hero"><div><small>THE 2026 COURSE EDIT</small><h2>Play bold.<br>Carry less.</h2><p>Thoughtful golf equipment for players who care how it performs and how it looks.</p><div class="site-actions"><button class="primary" data-page="shop">Shop the collection</button><button data-page="journal">Read the field notes</button></div></div><img src="./assets/golf-products.svg" alt="Original illustration of golf clubs, ball, bag, and fairway"></section><section class="site-section fairway-strip"><h3>Course-ready favorites</h3><div class="product-grid">${products.slice(0,3).map(productCard).join('')}</div></section>`;else if(page==='shop')c.innerHTML=`<section class="site-section"><div class="shop-heading"><div><small>SHOP ALL</small><h3>Equipment with a point of view.</h3></div><div class="shop-filters">${['All','Clubs','Bags','Accessories','Apparel'].map(x=>`<button data-filter="${x}" class="${x==='All'?'active':''}">${x}</button>`).join('')}</div></div><div class="product-grid" data-products>${products.map(productCard).join('')}</div></section>`;else if(page==='journal')c.innerHTML=`<section class="site-section fairway-journal"><small>FIELD NOTES</small><h3>Stories from the first tee.</h3><div class="site-grid">${[['A better 20-minute warmup','Practice'],['What actually belongs in a Sunday bag','Gear'],['Playing smart in Midwest wind','Course management']].map((x,i)=>`<article class="site-card"><div class="journal-image j${i}"></div><small>${x[1]}</small><h4>${x[0]}</h4><p>Practical advice for golfers who want more useful rounds and less noise.</p><button>Read story →</button></article>`).join('')}</div></section>`;else c.innerHTML=`<section class="site-hero fairway-about"><div><small>OUR STORY</small><h2>Golf retail without the country-club attitude.</h2><p>Bradley’s Fairway is a demonstration of a welcoming, editorial golf shop built around useful equipment and straightforward service.</p><div class="fairway-values"><span>Independent</span><span>Accessible</span><span>Player-first</span></div></div><img src="./assets/golf-products.svg" alt="Golf equipment illustration"></section>`;};
  const resetPages=wirePages(stage,render);function renderCart(){const wrap=$(stage,'[data-cart-items]');wrap.innerHTML=cart.length?cart.map((p,i)=>`<article><span class="cart-swatch" style="--product:${p.color}"></span><div><strong>${p.name}</strong><small>$${p.price}</small></div><button data-remove="${i}">Remove</button></article>`).join(''):'<p>Your bag is empty.</p>';$(stage,'[data-cart-count]').textContent=cart.length;$(stage,'[data-cart-total]').textContent=`$${cart.reduce((a,p)=>a+p.price,0)}`;}
  stage.addEventListener('click',e=>{const add=e.target.closest('[data-add]');if(add){cart.push(products[Number(add.dataset.add)]);renderCart();toast(`${products[Number(add.dataset.add)].name} added`);}const remove=e.target.closest('[data-remove]');if(remove){cart.splice(Number(remove.dataset.remove),1);renderCart();}if(e.target.closest('[data-cart]'))$(stage,'[data-cart-drawer]').hidden=false;if(e.target.closest('[data-cart-close]'))$(stage,'[data-cart-drawer]').hidden=true;const filter=e.target.closest('[data-filter]');if(filter){$$ (stage,'[data-filter]').forEach(b=>b.classList.toggle('active',b===filter));const value=filter.dataset.filter;$(stage,'[data-products]').innerHTML=products.map((p,i)=>({p,i})).filter(x=>value==='All'||x.p.category===value).map(x=>productCard(x.p,x.i)).join('');}});return controller(stage,()=>{cart=[];renderCart();resetPages();});
}
