import { basicScene, ground, box, cylinder, sphere, label, line, material, createServerRack, createGolfFlag, createTree, createCreature, createTruck, createWarehouse, animateAlong, seeded, pulse } from '../../core/scene.js';
const $=(r,s)=>r.querySelector(s);const $$=(r,s)=>[...r.querySelectorAll(s)];
function overlay(kicker,title,copy){return`<div class="game-overlay" data-overlay><div class="game-overlay-card"><span>${kicker}</span><h2>${title}</h2><p>${copy}</p><button data-start>START</button></div></div>`;}
function gameRoot(title,kicker,stats,controls,copy){return`<div class="game-root"><canvas aria-label="${title} 3D game"></canvas><div class="game-hud"><div class="game-titleplate"><span>${kicker}</span><strong>${title}</strong></div><div class="game-stats">${stats.map(x=>`<div class="game-stat"><span>${x[0]}</span><strong data-stat="${x[1]}">${x[2]}</strong></div>`).join('')}</div><div class="game-controls">${controls}</div></div>${overlay(kicker,title,copy)}</div>`;}
function finish(stage,title,copy){const o=$(stage,'[data-overlay]');o.hidden=false;o.querySelector('h2').textContent=title;o.querySelector('p').textContent=copy;o.querySelector('[data-start]').textContent='PLAY AGAIN';}

export async function createCloudOpsGame({stage,toast}){
  stage.innerHTML=gameRoot('Cloud Ops Crisis','ON-CALL STRATEGY',[['UPTIME','uptime','100%'],['BUDGET','budget','$120'],['TRAFFIC','traffic','60 RPS'],['TIME','time','0:00']],`<button data-op="scale">Scale API · $18</button><button data-op="cache">Deploy cache · $25</button><button data-op="queue">Enable queue · $20</button><button data-op="repair" class="primary">Repair incident · $14</button>`,'Keep uptime above 70% for a 90-second shift. Traffic, incidents, budget, and architecture all matter.');
  const canvas=$(stage,'canvas'),ctx=basicScene(canvas,{clear:'#020916ff',radius:23,target:[0,2,0],bloomWeight:.28,glow:.75});const {scene,BABYLON}=ctx;ground(scene,{width:34,height:22,color:'#071526'});
  const racks=[];for(let i=0;i<5;i++){const r=createServerRack(scene,[-10+i*5,0,1],{name:`service-${i}`,frame:['#173d5a','#2f4b61','#3a315d','#4c3a28','#244d42'][i]});racks.push(r);label(scene,['EDGE','CACHE','API','QUEUE','DATABASE'][i],[-10+i*5,5.5,1],{width:3.1,height:.65,fontSize:43,border:['#38bdf8','#f59e0b','#a78bfa','#22d3ee','#34d399'][i]});}
  const requestRoot=new BABYLON.TransformNode('requestStream',scene);const particles=[];for(let i=0;i<16;i++){const p=sphere(scene,`request-${i}`,.18,[-15+i*.5,1.2,-4],'#67e8f9',{emissive:'#67e8f9',emissiveIntensity:1});particles.push(p);}
  let running=false,timer=null,elapsed=0,traffic=60,capacity=105,budget=120,uptime=100,incident=false,score=0,cache=false,queue=false;
  function render(){const val=(k,v)=>$(stage,`[data-stat="${k}"]`).textContent=v;val('uptime',`${uptime.toFixed(1)}%`);val('budget',`$${Math.round(budget)}`);val('traffic',`${Math.round(traffic)} RPS`);val('time',`${Math.floor(elapsed/60)}:${String(Math.floor(elapsed%60)).padStart(2,'0')}`);racks[2].scaling.y=1+Math.max(0,traffic-capacity)/180;racks[2].getChildMeshes().forEach(m=>{if(m.material?.emissiveColor)m.material.emissiveIntensity=traffic>capacity?.8:.2;});}
  function tick(){if(!running)return;elapsed+=.5;traffic+=1.4+elapsed*.012;budget+=.28;if(Math.random()<.025&&!incident){incident=true;toast('SEV-2 database incident opened');racks[4].getChildMeshes().forEach(m=>m.material&&(m.material.emissiveColor=BABYLON.Color3.FromHexString('#ff4d6d')));}const overload=Math.max(0,traffic-capacity);uptime=Math.max(0,Math.min(100,uptime-overload*.006-(incident?.06:0)+.025));score+=uptime*.06;particles.forEach((p,i)=>{p.position.x+=.12+(traffic/800);if(p.position.x>15)p.position.x=-15;p.position.z=-4+Math.sin(i+elapsed*.2)*.8;});if(uptime<70||elapsed>=90){running=false;clearInterval(timer);finish(stage,uptime<70?'SERVICE OUTAGE':'SHIFT COMPLETE',`Score ${Math.round(score)} · final uptime ${uptime.toFixed(1)}%.`);}render();}
  function spend(amount,fn){if(!running||budget<amount)return;budget-=amount;fn();render();}
  $$ (stage,'[data-op]').forEach(b=>b.addEventListener('click',()=>{const op=b.dataset.op;if(op==='scale')spend(18,()=>{capacity+=50;toast('API capacity increased');});if(op==='cache')spend(25,()=>{if(!cache){cache=true;traffic*=.82;toast('Cache deployed');racks[1].scaling.setAll(1.08);}});if(op==='queue')spend(20,()=>{if(!queue){queue=true;capacity+=30;toast('Queue enabled');racks[3].scaling.setAll(1.08);}});if(op==='repair'&&incident)spend(14,()=>{incident=false;toast('Incident resolved');});}));
  function start(){clearInterval(timer);elapsed=0;traffic=60;capacity=105;budget=120;uptime=100;incident=false;score=0;cache=false;queue=false;running=true;$(stage,'[data-overlay]').hidden=true;timer=setInterval(tick,500);render();}
  $(stage,'[data-start]').addEventListener('click',start);render();return{dispose(){clearInterval(timer);ctx.dispose();},reset:start,getStats(){return ctx.stats('BABYLON.JS CLOUD STRATEGY');}};
}
