import { basicScene, ground, box, cylinder, sphere, label, line, material, createServerRack, createGolfFlag, createTree, createCreature, createTruck, createWarehouse, animateAlong, seeded, pulse } from '../../core/scene.js';
const $=(r,s)=>r.querySelector(s);const $$=(r,s)=>[...r.querySelectorAll(s)];
function overlay(kicker,title,copy){return`<div class="game-overlay" data-overlay><div class="game-overlay-card"><span>${kicker}</span><h2>${title}</h2><p>${copy}</p><button data-start>START</button></div></div>`;}
function gameRoot(title,kicker,stats,controls,copy){return`<div class="game-root"><canvas aria-label="${title} 3D game"></canvas><div class="game-hud"><div class="game-titleplate"><span>${kicker}</span><strong>${title}</strong></div><div class="game-stats">${stats.map(x=>`<div class="game-stat"><span>${x[0]}</span><strong data-stat="${x[1]}">${x[2]}</strong></div>`).join('')}</div><div class="game-controls">${controls}</div></div>${overlay(kicker,title,copy)}</div>`;}
function finish(stage,title,copy){const o=$(stage,'[data-overlay]');o.hidden=false;o.querySelector('h2').textContent=title;o.querySelector('p').textContent=copy;o.querySelector('[data-start]').textContent='PLAY AGAIN';}

export async function createCodeDungeon({stage,toast}){
  stage.innerHTML=gameRoot('Code Dungeon','3D SOFTWARE ROGUELIKE',[['BUGS','bugs','0 / 3'],['HEALTH','health','100'],['ROOM','room','ENTRY'],['BUILD','build','FAILING']],`<button data-move="up">↑</button><button data-move="left">←</button><button data-move="down">↓</button><button data-move="right">→</button>`,'Explore with WASD, arrow keys, or the controls. Collect three failing tests, avoid regression traps, then enter the production portal.');
  const canvas=$(stage,'canvas'),ctx=basicScene(canvas,{clear:'#05040aff',radius:18,target:[0,1,0],alpha:-Math.PI/2,beta:.82,bloomWeight:.26,glow:.75});const {scene,BABYLON,camera}=ctx;camera.inputs.clear();ground(scene,{width:26,height:20,color:'#121020'});const map=['#############','#P..#...B...#','#.#.#.#####.#','#.#...#.....#','#.###.#.###.#','#...#...#B#.#','###.#####.#.#','#B..........X','#############'];const cell=2,startCell={x:1,y:1};let player={x:startCell.x,y:startCell.y},bugs=new Set(),health=100,running=false;const originX=-12,originZ=-8;const bugMeshes=new Map();
  map.forEach((row,y)=>[...row].forEach((v,x)=>{const px=originX+x*cell,pz=originZ+y*cell;if(v==='#'){const wall=box(scene,`wall-${x}-${y}`,[1.85,2.5,1.85],[px,1.25,pz],'#30284c',{metallic:.15,roughness:.68,emissive:'#5b21b6',emissiveIntensity:.08});}else{const tile=box(scene,`tile-${x}-${y}`,[1.85,.12,1.85],[px,.05,pz],(x+y)%2?'#18132a':'#21193a',{roughness:.9});if(v==='B'){const b=sphere(scene,`bug-${x}-${y}`,.65,[px,.75,pz],'#ff4d8d',{emissive:'#ff4d8d',emissiveIntensity:1});pulse(b,scene,{range:.12,speed:4});bugMeshes.set(`${x},${y}`,b);}if(v==='X'){const portal=BABYLON.MeshBuilder.CreateTorus('productionPortal',{diameter:1.5,thickness:.22,tessellation:48},scene);portal.position.set(px,1.1,pz);portal.rotation.x=Math.PI/2;portal.material=material(scene,'portalMat','#34d399',{emissive:'#34d399',emissiveIntensity:1.2,metallic:.25,roughness:.2});label(scene,'PRODUCTION',[px,3,pz],{width:2.6,height:.55,fontSize:38,border:'#34d399'});}}}));
  const avatar=cylinder(scene,'player',.9,1.5,[originX+cell,.8,originZ+cell],'#67e8f9',{emissive:'#67e8f9',emissiveIntensity:.3,metallic:.2,roughness:.45});const head=sphere(scene,'playerHead',.65,[0,1.2,0],'#f0c39b',{roughness:.8});head.parent=avatar;camera.alpha=-Math.PI/2;camera.beta=.72;camera.radius=13;camera.setTarget(avatar.position);
  function render(){const room=player.y<3?'ENTRY':player.y<6?'TEST SUITE':'DEPLOYMENT';$(stage,'[data-stat="bugs"]').textContent=`${bugs.size} / 3`;$(stage,'[data-stat="health"]').textContent=health;$(stage,'[data-stat="room"]').textContent=room;$(stage,'[data-stat="build"]').textContent=bugs.size===3?'READY':'FAILING';avatar.position.x=originX+player.x*cell;avatar.position.z=originZ+player.y*cell;camera.setTarget(avatar.position);}
  function move(dx,dy){if(!running)return;const nx=player.x+dx,ny=player.y+dy,v=map[ny]?.[nx];if(!v||v==='#')return;player={x:nx,y:ny};const key=`${nx},${ny}`;if(v==='B'&&!bugs.has(key)){bugs.add(key);bugMeshes.get(key)?.dispose();toast('Failing test collected');}if((nx+ny)%7===0){health=Math.max(0,health-12);toast('Regression trap: -12 health');}if(v==='X'){if(bugs.size===3)finish(stage,'BUILD SHIPPED','All failing tests were collected and the production portal accepted the build.');else toast('Production is locked until all three bugs are collected.');}render();}
  const keys={ArrowUp:[0,-1],w:[0,-1],ArrowDown:[0,1],s:[0,1],ArrowLeft:[-1,0],a:[-1,0],ArrowRight:[1,0],d:[1,0]};const keyHandler=e=>{const m=keys[e.key];if(m){e.preventDefault();move(...m);}};window.addEventListener('keydown',keyHandler);$$ (stage,'[data-move]').forEach(b=>b.addEventListener('click',()=>move(...{up:[0,-1],down:[0,1],left:[-1,0],right:[1,0]}[b.dataset.move])));
  function start(){running=true;player={...startCell};bugs.clear();health=100;for(const [key,mesh] of bugMeshes)if(mesh.isDisposed()){const [x,y]=key.split(',').map(Number),b=sphere(scene,`bug-${x}-${y}-${Date.now()}`,.65,[originX+x*cell,.75,originZ+y*cell],'#ff4d8d',{emissive:'#ff4d8d',emissiveIntensity:1});bugMeshes.set(key,b);}$(stage,'[data-overlay]').hidden=true;render();}
  $(stage,'[data-start]').addEventListener('click',start);render();return{dispose(){window.removeEventListener('keydown',keyHandler);ctx.dispose();},reset:start,getStats(){return ctx.stats('BABYLON.JS 3D DUNGEON');}};
}
