import { basicScene, ground, box, cylinder, sphere, label, line, material, createServerRack, createGolfFlag, createTree, createCreature, createTruck, createWarehouse, animateAlong, seeded, pulse } from '../../core/scene.js';
const $=(r,s)=>r.querySelector(s);const $$=(r,s)=>[...r.querySelectorAll(s)];
function overlay(kicker,title,copy){return`<div class="game-overlay" data-overlay><div class="game-overlay-card"><span>${kicker}</span><h2>${title}</h2><p>${copy}</p><button data-start>START</button></div></div>`;}
function gameRoot(title,kicker,stats,controls,copy){return`<div class="game-root"><canvas aria-label="${title} 3D game"></canvas><div class="game-hud"><div class="game-titleplate"><span>${kicker}</span><strong>${title}</strong></div><div class="game-stats">${stats.map(x=>`<div class="game-stat"><span>${x[0]}</span><strong data-stat="${x[1]}">${x[2]}</strong></div>`).join('')}</div><div class="game-controls">${controls}</div></div>${overlay(kicker,title,copy)}</div>`;}
function finish(stage,title,copy){const o=$(stage,'[data-overlay]');o.hidden=false;o.querySelector('h2').textContent=title;o.querySelector('p').textContent=copy;o.querySelector('[data-start]').textContent='PLAY AGAIN';}

export async function createEvolutionGame({stage,toast}){
  stage.innerHTML=gameRoot('Digital Species Evolution','3D EVOLUTION SANDBOX',[['POPULATION','population','0'],['GENERATION','generation','1'],['AVG SPEED','speed','0'],['FOOD','food','0']],`<label>Mutation <input data-mutation type="range" min="1" max="30" value="10"></label><label>Food <input data-food-rate type="range" min="10" max="80" value="42"></label><button data-pressure>Toggle drought</button>`,'Run a living 3D ecosystem. Creatures seek food, spend energy, reproduce with inherited traits, mutate, and die.');
  const canvas=$(stage,'canvas'),ctx=basicScene(canvas,{clear:'#07140eff',radius:25,target:[0,0,0],alpha:-Math.PI/2,beta:.85,bloomWeight:.12,glow:.35});const {scene,BABYLON}=ctx;ground(scene,{width:32,height:24,color:'#315f3a'});const pond=BABYLON.MeshBuilder.CreateDisc('pond',{radius:4,tessellation:48},scene);pond.rotation.x=Math.PI/2;pond.position.set(7,.04,2);pond.scaling.z=.65;pond.material=material(scene,'pondMat','#2d8fb8',{metallic:.05,roughness:.18,alpha:.86});let creatures=[],foods=[],timer=null,running=false,generation=1,drought=false,rnd=seeded(9482),selected=null;
  function addFood(){const mesh=sphere(scene,`food-${Date.now()}-${foods.length}`,.3,[rnd()*28-14,.25,rnd()*20-10],'#fbbf24',{emissive:'#fbbf24',emissiveIntensity:.35});foods.push({mesh});}
  function addCreature(parent){const trait=parent?{speed:Math.max(.03,parent.speed+(rnd()-.5)*.02*(Number($(stage,'[data-mutation]').value)/10)),size:Math.max(.65,Math.min(1.55,parent.size+(rnd()-.5)*.18)),sense:Math.max(3,parent.sense+(rnd()-.5)*1.2),color:parent.color}:{speed:.055+rnd()*.035,size:.75+rnd()*.45,sense:4+rnd()*4,color:['#34d399','#67e8f9','#a78bfa','#fb7185'][Math.floor(rnd()*4)]};const root=createCreature(scene,[rnd()*24-12,0,rnd()*17-8.5],{name:`creature-${Date.now()}-${creatures.length}`,color:trait.color,size:trait.size,limbs:4+(rnd()>.7?2:0),glow:true});root.getChildMeshes().forEach(m=>{m.isPickable=true;m.metadata=trait;});creatures.push({...trait,root,energy:70+rnd()*30,age:0,repro:0});}
  for(let i=0;i<14;i++)addCreature();for(let i=0;i<35;i++)addFood();
  function render(){const avg=creatures.length?creatures.reduce((a,c)=>a+c.speed,0)/creatures.length:0;$(stage,'[data-stat="population"]').textContent=creatures.length;$(stage,'[data-stat="generation"]').textContent=generation;$(stage,'[data-stat="speed"]').textContent=avg.toFixed(3);$(stage,'[data-stat="food"]').textContent=foods.length;}
  function tick(){if(!running)return;const rate=Number($(stage,'[data-food-rate]').value);if(Math.random()<rate/1000*(drought?.25:1))addFood();creatures.forEach(c=>{c.age++;c.energy-=.13+c.speed*1.2+c.size*.03;let target=null,best=c.sense;foods.forEach(f=>{const d=BABYLON.Vector3.Distance(c.root.position,f.mesh.position);if(d<best){best=d;target=f;}});if(target){const dir=target.mesh.position.subtract(c.root.position);c.root.position.addInPlace(dir.normalize().scale(c.speed));c.root.rotation.y=Math.atan2(dir.x,dir.z);if(best<.55){c.energy=Math.min(120,c.energy+28);target.eaten=true;target.mesh.dispose();c.repro++;}}else{c.root.position.x+=Math.sin(c.age*.05+c.speed*100)*c.speed*.35;c.root.position.z+=Math.cos(c.age*.04+c.size)*c.speed*.35;}if(c.repro>=3&&c.energy>75&&creatures.length<55){c.energy-=30;c.repro=0;addCreature(c);if(creatures.length%8===0)generation++;}if(c.energy<=0||c.age>4200){c.dead=true;c.root.dispose();}});foods=foods.filter(f=>!f.eaten);creatures=creatures.filter(c=>!c.dead);if(creatures.length<4){for(let i=0;i<7;i++)addCreature();generation++;toast('Population bottleneck: new founders introduced');}render();}
  $(stage,'[data-pressure]').addEventListener('click',e=>{drought=!drought;e.target.textContent=drought?'End drought':'Toggle drought';toast(drought?'Drought pressure enabled':'Food conditions restored');});const observer=scene.onPointerObservable.add(e=>{if(e.type!==BABYLON.PointerEventTypes.POINTERPICK)return;const trait=e.pickInfo?.pickedMesh?.metadata;if(trait)toast(`Creature · speed ${trait.speed.toFixed(3)} · size ${trait.size.toFixed(2)} · sense ${trait.sense.toFixed(1)}`);});function start(){clearInterval(timer);running=true;$(stage,'[data-overlay]').hidden=true;timer=setInterval(tick,30);render();}
  $(stage,'[data-start]').addEventListener('click',start);render();return{dispose(){clearInterval(timer);scene.onPointerObservable.remove(observer);ctx.dispose();},reset(){creatures.forEach(c=>c.root.dispose());foods.forEach(f=>f.mesh.dispose());creatures=[];foods=[];generation=1;for(let i=0;i<14;i++)addCreature();for(let i=0;i<35;i++)addFood();start();},getStats(){return ctx.stats('BABYLON.JS EVOLUTION ENGINE');}};
}
