import { basicScene, ground, box, cylinder, sphere, label, line, material, createServerRack, createGolfFlag, createTree, createCreature, createTruck, createWarehouse, animateAlong, seeded, pulse } from '../../core/scene.js';
const $=(r,s)=>r.querySelector(s);const $$=(r,s)=>[...r.querySelectorAll(s)];
function overlay(kicker,title,copy){return`<div class="game-overlay" data-overlay><div class="game-overlay-card"><span>${kicker}</span><h2>${title}</h2><p>${copy}</p><button data-start>START</button></div></div>`;}
function gameRoot(title,kicker,stats,controls,copy){return`<div class="game-root"><canvas aria-label="${title} 3D game"></canvas><div class="game-hud"><div class="game-titleplate"><span>${kicker}</span><strong>${title}</strong></div><div class="game-stats">${stats.map(x=>`<div class="game-stat"><span>${x[0]}</span><strong data-stat="${x[1]}">${x[2]}</strong></div>`).join('')}</div><div class="game-controls">${controls}</div></div>${overlay(kicker,title,copy)}</div>`;}
function finish(stage,title,copy){const o=$(stage,'[data-overlay]');o.hidden=false;o.querySelector('h2').textContent=title;o.querySelector('p').textContent=copy;o.querySelector('[data-start]').textContent='PLAY AGAIN';}

export async function createGolfGame({stage,toast}){
  stage.innerHTML=gameRoot('Fairway Target Challenge','3D TARGET GOLF',[['SCORE','score','0'],['SHOTS','shots','3'],['WIND','wind','--'],['DISTANCE','distance','165 yd']],`<label>Club <select data-club><option value="30">7 Iron</option><option value="25">9 Iron</option><option value="20">Wedge</option></select></label><label>Aim <input data-aim type="range" min="-22" max="22" value="0"></label><label>Power <input data-power type="range" min="35" max="100" value="78"></label><button data-swing class="primary">SWING</button>`,'Play three shots on a real 3D course. Read the wind, choose a club, aim, and land near the 165-yard pin.');
  const canvas=$(stage,'canvas'),ctx=basicScene(canvas,{clear:'#9ed5f0ff',radius:28,target:[0,1,8],alpha:-Math.PI/2,beta:1.18,bloomWeight:.08,glow:.25});const {scene,BABYLON,camera}=ctx;const fairway=ground(scene,{width:24,height:48,color:'#4d9b51',subdivisions:4});fairway.position.z=8;const rough=ground(scene,{name:'rough',width:38,height:60,color:'#2f6f3e'});rough.position.y=-.03;rough.position.z=8;const green=BABYLON.MeshBuilder.CreateDisc('green',{radius:7,tessellation:64},scene);green.rotation.x=Math.PI/2;green.position.set(0,.03,25);green.scaling.z=.68;green.material=material(scene,'greenMat','#74bd65',{roughness:.95});createGolfFlag(scene,[0,0,25],{color:'#ef4444'});for(let i=0;i<22;i++){const side=i%2?-1:1;createTree(scene,[side*(9+(i%3)*1.7),0,-12+i*2.7],{scale:.7+(i%4)*.12,color:i%3?'#276e3c':'#3c8447'});}const bunker=BABYLON.MeshBuilder.CreateDisc('bunker',{radius:3.3,tessellation:48},scene);bunker.rotation.x=Math.PI/2;bunker.position.set(-5,.05,21);bunker.scaling.z=.55;bunker.material=material(scene,'sandMat','#d9c38c',{roughness:1});let ball=sphere(scene,'golfBall',.42,[0,.24,-16],'#ffffff',{metallic:.03,roughness:.35});let trail=[];let running=false,shots=3,score=0,wind=0,frame=null,velocity=new BABYLON.Vector3(),last=0;
  function render(){const set=(k,v)=>$(stage,`[data-stat="${k}"]`).textContent=v;set('score',score);set('shots',shots);set('wind',`${Math.abs(wind).toFixed(1)} mph ${wind<0?'W':'E'}`);}
  function loop(t){if(!running)return;const dt=Math.min(.025,(t-last)/1000||.016);last=t;if(ball.metadata?.flying){velocity.y-=9.81*dt*.26;velocity.x+=wind*.0025*dt;ball.position.addInPlace(velocity.scale(dt));trail.push(ball.position.clone());if(trail.length>100)trail.shift();camera.target=BABYLON.Vector3.Lerp(camera.target,ball.position,.05);if(ball.position.y<=.22&&velocity.y<0){ball.position.y=.22;velocity.y*=-.28;velocity.x*=.72;velocity.z*=.72;if(Math.abs(velocity.y)<.35){ball.metadata.flying=false;const dist=Math.hypot(ball.position.x,ball.position.z-25),points=Math.max(0,Math.round(1000-dist*55));score+=points;toast(`${points} points · ${dist.toFixed(1)} yards from pin`);if(shots<=0)finish(stage,'ROUND COMPLETE',`Final score ${score}. Your last ball finished ${dist.toFixed(1)} yards from the pin.`);else setTimeout(()=>{ball.position.set(0,.24,-16);camera.setTarget(new BABYLON.Vector3(0,1,8));camera.radius=28;},700);}}}frame=requestAnimationFrame(loop);}
  $(stage,'[data-swing]').addEventListener('click',()=>{if(!running||ball.metadata?.flying||shots<=0)return;shots--;const power=Number($(stage,'[data-power]').value)/100,club=Number($(stage,'[data-club]').value),aim=Number($(stage,'[data-aim]').value)*Math.PI/180;velocity.set(Math.sin(aim)*club*.18,club*.24*power,Math.cos(aim)*club*.62*power);ball.metadata={flying:true};render();});
  function start(){cancelAnimationFrame(frame);shots=3;score=0;wind=Math.random()*12-6;running=true;ball.position.set(0,.24,-16);ball.metadata={flying:false};camera.setTarget(new BABYLON.Vector3(0,1,8));camera.radius=28;$(stage,'[data-overlay]').hidden=true;last=performance.now();frame=requestAnimationFrame(loop);render();}
  $(stage,'[data-start]').addEventListener('click',start);render();return{dispose(){running=false;cancelAnimationFrame(frame);ctx.dispose();},reset:start,getStats(){return ctx.stats('BABYLON.JS 3D GOLF PHYSICS');}};
}
