import { basicScene, ground, box, cylinder, sphere, label, line, material, createAgent, createDesk, createServerRack, animateAlong, pulse } from '../../core/scene.js';

const $=(root,s)=>root.querySelector(s);
const $$=(root,s)=>[...root.querySelectorAll(s)];
const wait=ms=>new Promise(r=>setTimeout(r,ms));
function domController(stage, reset, cleanup, engine='INTERACTIVE SIMULATION') { return { dispose(){cleanup?.();stage.replaceChildren();}, reset, getStats(){return {engine,fps:'DOM',scene:`${stage.querySelectorAll('*').length} UI elements`};} }; }

export function createProjectHubRag({stage,toast}){
  const docs=[{name:'AWS Internship.md',score:.94,excerpt:'Cloud Support Associate internship, May–August 2025…'},{name:'Certifications.json',score:.91,excerpt:'AWS Solutions Architect Associate and AI Practitioner…'},{name:'ProjectHub README',score:.86,excerpt:'Grounded recruiter assistant with deterministic facts…'},{name:'Resume.pdf',score:.81,excerpt:'Full-stack software engineer, cloud support, frontend…'}];
  stage.innerHTML=`<section class="rag-studio"><header><div><span>PROJECTHUB</span><strong>Evidence Retrieval Studio</strong></div><button data-run>Run recruiter question</button></header><div class="rag-query"><label>QUESTION<input data-query value="What cloud support experience and AWS certifications does Brad have?"></label><div class="rag-stage-strip">${['CLASSIFY','RETRIEVE','RERANK','CONSTRUCT','GENERATE','JUDGE'].map((x,i)=>`<div data-rag-step="${i}"><span>${String(i+1).padStart(2,'0')}</span><strong>${x}</strong><small>waiting</small></div>`).join('')}</div></div><div class="rag-workspace"><section><h3>RETRIEVED EVIDENCE</h3><div data-documents class="document-stack"><p>Run the question to retrieve evidence.</p></div></section><section class="context-window"><h3>CONTEXT WINDOW</h3><pre data-context>No context constructed.</pre></section><section class="answer-preview"><h3>GROUNDED ANSWER</h3><article data-answer><p>No answer generated.</p></article><footer data-judge>Judge: waiting</footer></section></div></section>`;
  let running=false;
  async function run(){if(running)return;running=true;const steps=$$ (stage,'[data-rag-step]');steps.forEach(s=>{s.className='';s.querySelector('small').textContent='waiting';});$(stage,'[data-documents]').innerHTML='';$(stage,'[data-context]').textContent='';$(stage,'[data-answer]').innerHTML='<p>Generating…</p>';for(let i=0;i<steps.length;i++){steps[i].classList.add('active');steps[i].querySelector('small').textContent='running';await wait(550);if(i===0)steps[i].querySelector('small').textContent='recruiter / AWS';if(i===1){$(stage,'[data-documents]').innerHTML=docs.map(d=>`<article><span>${Math.round(d.score*100)}%</span><strong>${d.name}</strong><p>${d.excerpt}</p></article>`).join('');steps[i].querySelector('small').textContent='4 sources';}if(i===2)steps[i].querySelector('small').textContent='top 3 selected';if(i===3){$(stage,'[data-context]').textContent='FACT 1: AWS Cloud Support Associate Intern, May 27–Aug 18, 2025.\nFACT 2: Lab-based support engineering training; no production tickets.\nFACT 3: AWS SAA and AI Practitioner certified.\nFACT 4: Built a serverless DynamoDB metadata capstone.';steps[i].querySelector('small').textContent='672 tokens';}if(i===4){$(stage,'[data-answer]').innerHTML='<p>Brad completed a 12-week AWS Cloud Support Associate internship in Seattle in 2025. The program used isolated lab accounts rather than production tickets, and included troubleshooting, AWS service labs, and a serverless DynamoDB metadata capstone. He also holds the AWS Solutions Architect – Associate and AWS Certified AI Practitioner certifications.</p><ol><li>AWS Internship.md</li><li>Certifications.json</li><li>ProjectHub README</li></ol>';steps[i].querySelector('small').textContent='grounded answer';}if(i===5){$(stage,'[data-judge]').textContent='Judge: PASS · 0 unsupported claims · 3 citations';steps[i].querySelector('small').textContent='PASS';toast('Grounded answer verified');}steps[i].classList.remove('active');steps[i].classList.add('done');}running=false;}
  $(stage,'[data-run]').addEventListener('click',run);
  return domController(stage,()=>{running=false;$$ (stage,'[data-rag-step]').forEach(s=>{s.className='';s.querySelector('small').textContent='waiting';});$(stage,'[data-documents]').innerHTML='<p>Run the question to retrieve evidence.</p>';$(stage,'[data-context]').textContent='No context constructed.';$(stage,'[data-answer]').innerHTML='<p>No answer generated.</p>';$(stage,'[data-judge]').textContent='Judge: waiting';},null,'RETRIEVAL PIPELINE');
}
