import { basicScene, ground, box, cylinder, sphere, label, line, material, createAgent, createDesk, createServerRack, animateAlong, pulse } from '../../core/scene.js';

const $=(root,s)=>root.querySelector(s);
const $$=(root,s)=>[...root.querySelectorAll(s)];
const wait=ms=>new Promise(r=>setTimeout(r,ms));
function domController(stage, reset, cleanup, engine='INTERACTIVE SIMULATION') { return { dispose(){cleanup?.();stage.replaceChildren();}, reset, getStats(){return {engine,fps:'DOM',scene:`${stage.querySelectorAll('*').length} UI elements`};} }; }

export function createVoiceOps({stage,toast}){
  const calls=[
    {name:'Sarah Mitchell',number:'815-555-0128',intent:'Schedule consultation',sentiment:'Positive',agent:'Maya',time:'00:42'},
    {name:'Derek Wallace',number:'608-555-0184',intent:'Support escalation',sentiment:'Concerned',agent:'Derek',time:'02:18'},
    {name:'Unknown caller',number:'312-555-0199',intent:'Pricing inquiry',sentiment:'Neutral',agent:'Frank',time:'00:16'},
  ];
  stage.innerHTML=`<section class="voice-product"><header><div><span>VOICE OPS</span><strong>Live Call Floor</strong></div><div class="voice-kpis"><b>3 LIVE</b><b>18 WAITING</b><b>92% SLA</b></div></header><div class="voice-layout"><aside class="call-queue">${calls.map((c,i)=>`<button data-call="${i}" class="${i===0?'active':''}"><i></i><span><strong>${c.name}</strong><small>${c.intent}</small></span><em>${c.time}</em></button>`).join('')}</aside><main class="call-focus"><div class="caller-card"><div class="avatar">SM</div><div><small>ACTIVE CALL</small><h2 data-caller>${calls[0].name}</h2><p data-number>${calls[0].number}</p></div><div class="call-time" data-time>${calls[0].time}</div></div><div class="waveform">${Array.from({length:52},(_,i)=>`<i style="--h:${18+(i*17)%64}%"></i>`).join('')}</div><div class="transcript" data-transcript><p><b>Agent:</b> Thanks for calling Matera Digital. How can I help?</p><p><b>Caller:</b> I’d like to schedule a consultation about a new website.</p></div><div class="call-actions"><button data-voice="hold">Hold</button><button data-voice="transfer">Transfer</button><button data-voice="appointment">Schedule</button><button data-voice="resolve">Resolve call</button></div></main><aside class="call-intelligence"><h3>CALL INTELLIGENCE</h3><dl><div><dt>INTENT</dt><dd data-intent>${calls[0].intent}</dd></div><div><dt>SENTIMENT</dt><dd data-sentiment>${calls[0].sentiment}</dd></div><div><dt>ASSIGNED</dt><dd data-agent>${calls[0].agent}</dd></div><div><dt>CONFIDENCE</dt><dd>94%</dd></div></dl><h3>LIVE SUMMARY</h3><p data-summary>Qualified web-design lead requesting a consultation. No escalation required.</p><ol data-events><li>Call answered by Maya.</li></ol></aside></div></section>`;
  let selected=0,timer=setInterval(()=>{$$ (stage,'.waveform i').forEach((bar,i)=>bar.style.setProperty('--h',`${15+Math.random()*75}%`));},220);
  function show(i){selected=i;const c=calls[i];$$ (stage,'[data-call]').forEach((b,n)=>b.classList.toggle('active',n===i));$(stage,'[data-caller]').textContent=c.name;$(stage,'[data-number]').textContent=c.number;$(stage,'[data-time]').textContent=c.time;$(stage,'[data-intent]').textContent=c.intent;$(stage,'[data-sentiment]').textContent=c.sentiment;$(stage,'[data-agent]').textContent=c.agent;$(stage,'[data-transcript]').innerHTML=i===1?'<p><b>Caller:</b> My API stopped responding after the deployment.</p><p><b>Agent:</b> I’m escalating this to technical support now.</p>':i===2?'<p><b>Caller:</b> What does a custom site usually cost?</p><p><b>Agent:</b> I can collect your project details and prepare an estimate.</p>':'<p><b>Agent:</b> Thanks for calling Matera Digital. How can I help?</p><p><b>Caller:</b> I’d like to schedule a consultation about a new website.</p>';}
  $$ (stage,'[data-call]').forEach(b=>b.addEventListener('click',()=>show(Number(b.dataset.call))));
  $$ (stage,'[data-voice]').forEach(b=>b.addEventListener('click',()=>{const action=b.dataset.voice;const text={hold:'Caller placed on hold.',transfer:`Transferred to ${selected===1?'technical support':'sales'}.`,appointment:'Consultation scheduled for Thursday at 10:00 AM.',resolve:'Call resolved and summary saved.'}[action];$(stage,'[data-events]').insertAdjacentHTML('afterbegin',`<li>${text}</li>`);toast(text);}));
  return domController(stage,()=>show(0),()=>clearInterval(timer),'VOICE OPERATIONS UI');
}
