const GAME_CONFIG = {
  "cloud-ops-crisis": { title: "Cloud Ops Crisis", accent: "#71e5ff", description: "Keep a live service online while traffic rises, incidents spread, and the operating budget tightens.", instructions: "Choose upgrades and respond to incidents before uptime collapses." },
  "golf-challenge": { title: "Fairway Target Challenge", accent: "#d8ff72", description: "A lightweight target-golf game with wind, club selection, launch physics, scoring, and three-shot rounds.", instructions: "Set angle and power, account for wind, then swing." },
  "code-dungeon": { title: "Code Dungeon", accent: "#b68cff", description: "Navigate a procedural software dungeon, collect failing tests, avoid regressions, and reach production.", instructions: "Use WASD or arrow keys. Collect all red bugs before entering the deploy portal." },
  "data-center-defense": { title: "Data Center Defense", accent: "#ff7fa8", description: "Protect the origin server from traffic storms by placing cache nodes along the request lanes.", instructions: "Click empty sockets to place defenses. Survive every traffic wave." },
  "digital-evolution": { title: "Digital Species Evolution", accent: "#88f5a7", description: "Autonomous organisms search for energy, reproduce, mutate, and pass successful traits into later generations.", instructions: "Adjust mutation pressure, add food, or accelerate the simulation." },
  "pcs-logistics": { title: "PCS Logistics Challenge", accent: "#ff9a62", description: "Route a small fleet across changing jobs while balancing fuel, deadlines, distance, and capacity.", instructions: "Assign available trucks to the best jobs before contracts expire." },
};

function gameShell(config, controls = "") {
  return `<section class="demo-surface game-surface" style="--demo-accent:${config.accent}">
    <header class="surface-header game-header"><div><p class="surface-kicker">PLAYABLE BROWSER GAME</p><h2>${config.title}</h2><p>${config.description}</p></div><div class="game-scoreboard"><article><span>SCORE</span><strong data-game-score>0</strong></article><article><span>STATUS</span><strong data-game-status>READY</strong></article></div></header>
    <div class="game-layout"><main class="game-stage"><canvas width="1100" height="650" data-game-canvas tabindex="0" aria-label="${config.title} game canvas"></canvas><div class="game-overlay" data-game-overlay><strong>${config.title}</strong><p>${config.instructions}</p><button data-game-start>START GAME</button></div></main><aside class="game-controls">${controls}<div class="game-log"><header>MISSION LOG</header><ol data-game-log><li>Game ready.</li></ol></div></aside></div>
  </section>`;
}

function createCanvasContext(stage) {
  const canvas = stage.querySelector("[data-game-canvas]");
  const ctx = canvas.getContext("2d");
  const scoreNode = stage.querySelector("[data-game-score]");
  const statusNode = stage.querySelector("[data-game-status]");
  const overlay = stage.querySelector("[data-game-overlay]");
  const log = stage.querySelector("[data-game-log]");
  const addLog = (message) => { log.insertAdjacentHTML("afterbegin", `<li>${message}</li>`); while (log.children.length > 7) log.lastElementChild.remove(); };
  const setScore = (value) => { scoreNode.textContent = Math.round(value); };
  const setStatus = (value) => { statusNode.textContent = value; };
  const hideOverlay = () => { overlay.hidden = true; canvas.focus(); };
  const showOverlay = (title, copy, button = "PLAY AGAIN") => { overlay.hidden = false; overlay.querySelector("strong").textContent = title; overlay.querySelector("p").textContent = copy; overlay.querySelector("button").textContent = button; };
  return { canvas, ctx, setScore, setStatus, addLog, hideOverlay, showOverlay };
}

function setupCloudOps(stage) {
  const controls = stage.querySelector(".game-controls");
  controls.insertAdjacentHTML("afterbegin", `<section class="ops-panel"><header>SERVICE CONTROLS</header><article><span>UPTIME</span><strong data-ops-uptime>100%</strong><i><b data-ops-uptime-bar></b></i></article><article><span>BUDGET</span><strong data-ops-budget>$120</strong></article><article><span>CAPACITY</span><strong data-ops-capacity>100 rps</strong></article><button data-ops-action="scale">Scale +50 RPS <small>$18</small></button><button data-ops-action="cache">Enable cache <small>$25</small></button><button data-ops-action="repair">Repair incident <small>$14</small></button></section>`);
  const api = createCanvasContext(stage); let running = false; let frame; let last = 0; let elapsed = 0; let traffic = 55; let capacity = 100; let budget = 120; let uptime = 100; let cache = false; let incident = 0; let score = 0;
  const draw = () => { const { ctx, canvas } = api; ctx.fillStyle = "#06101a"; ctx.fillRect(0, 0, canvas.width, canvas.height); ctx.strokeStyle = "rgba(113,229,255,.12)"; ctx.lineWidth = 1; for (let x = 0; x < canvas.width; x += 50) { ctx.beginPath(); ctx.moveTo(x, 0); ctx.lineTo(x, canvas.height); ctx.stroke(); } for (let y = 0; y < canvas.height; y += 50) { ctx.beginPath(); ctx.moveTo(0, y); ctx.lineTo(canvas.width, y); ctx.stroke(); } const max = 320; const barX = 100; const barW = 850; ctx.fillStyle = "rgba(255,255,255,.05)"; ctx.fillRect(barX, 120, barW, 54); ctx.fillStyle = traffic > capacity ? "#ff7f8f" : "#71e5ff"; ctx.fillRect(barX, 120, Math.min(barW, traffic / max * barW), 54); ctx.fillStyle = "#f4f8fb"; ctx.font = "700 24px sans-serif"; ctx.fillText(`TRAFFIC ${Math.round(traffic)} RPS`, barX, 103); ctx.fillStyle = "#91a4b4"; ctx.font = "16px monospace"; ctx.fillText(`CAPACITY LIMIT ${capacity} RPS`, barX, 205); const nodes = [{ x: 160, name: "EDGE", ok: true }, { x: 390, name: cache ? "CACHE ON" : "CACHE OFF", ok: cache }, { x: 620, name: "API", ok: incident < 30 }, { x: 850, name: "DATABASE", ok: traffic < capacity * 1.2 }]; nodes.forEach((node, i) => { ctx.strokeStyle = node.ok ? "#71e5ff" : "#ff7f8f"; ctx.fillStyle = node.ok ? "rgba(113,229,255,.12)" : "rgba(255,127,143,.15)"; ctx.lineWidth = 3; ctx.fillRect(node.x - 72, 310, 144, 96); ctx.strokeRect(node.x - 72, 310, 144, 96); ctx.fillStyle = node.ok ? "#b7f3ff" : "#ffb3bd"; ctx.font = "700 16px monospace"; ctx.textAlign = "center"; ctx.fillText(node.name, node.x, 365); if (i < nodes.length - 1) { ctx.strokeStyle = "rgba(113,229,255,.35)"; ctx.beginPath(); ctx.moveTo(node.x + 72, 358); ctx.lineTo(nodes[i + 1].x - 72, 358); ctx.stroke(); } }); ctx.textAlign = "left"; ctx.fillStyle = incident > 0 ? "#ff9a62" : "#88f5a7"; ctx.font = "800 28px sans-serif"; ctx.fillText(incident > 0 ? `ACTIVE INCIDENT: SEVERITY ${Math.ceil(incident / 10)}` : "ALL SYSTEMS NOMINAL", 100, 520); ctx.fillStyle = "#91a4b4"; ctx.font = "17px sans-serif"; ctx.fillText("Traffic grows continuously. Capacity overload and unresolved incidents reduce uptime.", 100, 558); };
  const updateUi = () => { stage.querySelector("[data-ops-uptime]").textContent = `${uptime.toFixed(1)}%`; stage.querySelector("[data-ops-budget]").textContent = `$${Math.round(budget)}`; stage.querySelector("[data-ops-capacity]").textContent = `${capacity} rps`; stage.querySelector("[data-ops-uptime-bar]").style.width = `${uptime}%`; api.setScore(score); };
  const loop = (time) => { if (!running) return; const dt = Math.min(.04, (time - last) / 1000 || 0); last = time; elapsed += dt; traffic += dt * (4.8 + elapsed * .08); budget += dt * 1.5; if (cache) traffic -= dt * 1.7; if (Math.random() < dt * .055 && incident <= 0) { incident = 20 + Math.random() * 30; api.addLog("New downstream latency incident detected."); } if (incident > 0) incident += dt * 2.2; const overload = Math.max(0, traffic - capacity); uptime -= dt * (overload * .025 + incident * .012); uptime = Math.min(100, uptime + dt * .14); score += dt * uptime; updateUi(); draw(); if (uptime <= 50 || elapsed >= 90) { running = false; api.setStatus(uptime <= 50 ? "OUTAGE" : "SHIFT COMPLETE"); api.showOverlay(uptime <= 50 ? "SERVICE OUTAGE" : "SHIFT COMPLETE", `Final reliability score: ${Math.round(score)}. Keep capacity ahead of traffic and repair incidents quickly.`); return; } frame = requestAnimationFrame(loop); };
  stage.querySelectorAll("[data-ops-action]").forEach((button) => button.addEventListener("click", () => { const action = button.dataset.opsAction; if (action === "scale" && budget >= 18) { budget -= 18; capacity += 50; api.addLog("Capacity increased by 50 RPS."); } if (action === "cache" && budget >= 25 && !cache) { budget -= 25; cache = true; api.addLog("Edge cache enabled; origin pressure reduced."); button.disabled = true; } if (action === "repair" && budget >= 14 && incident > 0) { budget -= 14; incident = Math.max(0, incident - 26); api.addLog("Incident remediation applied."); } updateUi(); draw(); }));
  const start = () => { cancelAnimationFrame(frame); running = true; last = performance.now(); elapsed = 0; traffic = 55; capacity = 100; budget = 120; uptime = 100; cache = false; incident = 0; score = 0; stage.querySelector('[data-ops-action="cache"]').disabled = false; api.hideOverlay(); api.setStatus("LIVE"); updateUi(); draw(); frame = requestAnimationFrame(loop); };
  stage.querySelector("[data-game-start]").addEventListener("click", start); draw(); updateUi(); return () => cancelAnimationFrame(frame);
}

function setupGolf(stage) {
  const controls = stage.querySelector(".game-controls");
  controls.insertAdjacentHTML("afterbegin", `<section class="golf-panel"><header>SHOT CONTROL</header><label>Club<select data-golf-club><option value="1">Driver</option><option value="0.78">7 Iron</option><option value="0.48">Wedge</option></select></label><label>Launch angle <output data-golf-angle-output>38°</output><input type="range" min="15" max="65" value="38" data-golf-angle></label><label>Power <output data-golf-power-output>82%</output><input type="range" min="25" max="100" value="82" data-golf-power></label><article><span>WIND</span><strong data-golf-wind>--</strong></article><article><span>SHOTS LEFT</span><strong data-golf-shots>3</strong></article><button data-golf-swing>SWING</button></section>`);
  const api = createCanvasContext(stage); let frame; let ball = null; let shots = 3; let score = 0; let wind = 0; let running = false; const targetX = 850;
  const angle = stage.querySelector("[data-golf-angle]"); const power = stage.querySelector("[data-golf-power]");
  angle.addEventListener("input", () => stage.querySelector("[data-golf-angle-output]").textContent = `${angle.value}°`); power.addEventListener("input", () => stage.querySelector("[data-golf-power-output]").textContent = `${power.value}%`);
  const draw = () => { const { ctx, canvas } = api; const gradient = ctx.createLinearGradient(0, 0, 0, canvas.height); gradient.addColorStop(0, "#09233b"); gradient.addColorStop(.62, "#17495e"); gradient.addColorStop(.63, "#456e40"); gradient.addColorStop(1, "#183d28"); ctx.fillStyle = gradient; ctx.fillRect(0, 0, canvas.width, canvas.height); ctx.fillStyle = "rgba(255,255,255,.05)"; ctx.beginPath(); ctx.arc(160, 100, 58, 0, Math.PI * 2); ctx.fill(); ctx.fillStyle = "#6ea259"; ctx.beginPath(); ctx.ellipse(targetX, 528, 115, 34, 0, 0, Math.PI * 2); ctx.fill(); ctx.strokeStyle = "#f4f8fb"; ctx.lineWidth = 3; ctx.beginPath(); ctx.moveTo(targetX, 525); ctx.lineTo(targetX, 365); ctx.stroke(); ctx.fillStyle = "#d8ff72"; ctx.beginPath(); ctx.moveTo(targetX, 365); ctx.lineTo(targetX + 72, 389); ctx.lineTo(targetX, 413); ctx.fill(); [24, 55, 92].forEach((radius, index) => { ctx.strokeStyle = ["#d8ff72", "rgba(216,255,114,.62)", "rgba(216,255,114,.28)"][index]; ctx.lineWidth = 3; ctx.beginPath(); ctx.ellipse(targetX, 528, radius, radius * .28, 0, 0, Math.PI * 2); ctx.stroke(); }); ctx.fillStyle = "#fff"; ctx.beginPath(); ctx.arc(ball?.x || 105, ball?.y || 515, 10, 0, Math.PI * 2); ctx.fill(); ctx.strokeStyle = "rgba(255,255,255,.2)"; ctx.setLineDash([8, 8]); ctx.beginPath(); ctx.moveTo(105, 515); const previewAngle = Number(angle.value) * Math.PI / 180; const previewPower = Number(power.value) * 2.4; ctx.quadraticCurveTo(105 + Math.cos(previewAngle) * previewPower * 2.1, 515 - Math.sin(previewAngle) * previewPower * 2.3, 105 + previewPower * 3.4, 515); ctx.stroke(); ctx.setLineDash([]); ctx.fillStyle = "#f4f8fb"; ctx.font = "700 18px monospace"; ctx.fillText(`TARGET ${targetX - 105} YDS`, 54, 55); };
  const resetBall = () => { ball = { x: 105, y: 515, vx: 0, vy: 0, flying: false }; draw(); };
  const swing = () => { if (!running || ball.flying || shots <= 0) return; shots -= 1; stage.querySelector("[data-golf-shots]").textContent = shots; const a = Number(angle.value) * Math.PI / 180; const p = Number(power.value) * 5.4 * Number(stage.querySelector("[data-golf-club]").value); ball.vx = Math.cos(a) * p + wind * .08; ball.vy = -Math.sin(a) * p; ball.flying = true; api.addLog(`Shot ${3 - shots}: ${angle.value}° at ${power.value}% power.`); };
  const loop = () => { if (!running) return; if (ball.flying) { ball.vy += .22; ball.vx += wind * .0007; ball.x += ball.vx; ball.y += ball.vy; if (ball.y >= 515) { ball.y = 515; ball.flying = false; const distance = Math.abs(ball.x - targetX); const points = Math.max(0, Math.round(1000 - distance * 3)); score += points; api.setScore(score); api.addLog(`${points} points. Ball finished ${Math.round(distance)} yards from target.`); if (shots <= 0) { running = false; api.setStatus("ROUND COMPLETE"); api.showOverlay("ROUND COMPLETE", `Final score: ${score}. A perfect three-shot round is 3000 points.`); } else setTimeout(resetBall, 650); } } draw(); frame = requestAnimationFrame(loop); };
  stage.querySelector("[data-golf-swing]").addEventListener("click", swing);
  const start = () => { cancelAnimationFrame(frame); score = 0; shots = 3; wind = Math.round((Math.random() * 16 - 8) * 10) / 10; running = true; stage.querySelector("[data-golf-wind]").textContent = `${wind > 0 ? "→" : "←"} ${Math.abs(wind)} mph`; stage.querySelector("[data-golf-shots]").textContent = shots; api.setScore(0); api.setStatus("ON COURSE"); api.hideOverlay(); resetBall(); frame = requestAnimationFrame(loop); };
  stage.querySelector("[data-game-start]").addEventListener("click", start); resetBall(); return () => cancelAnimationFrame(frame);
}

function setupCodeDungeon(stage) {
  const controls = stage.querySelector(".game-controls"); controls.insertAdjacentHTML("afterbegin", `<section class="dungeon-panel"><header>BUILD STATUS</header><article><span>BUGS REMAINING</span><strong data-bugs-left>--</strong></article><article><span>HEALTH</span><strong data-code-health>3</strong></article><div class="key-guide"><i>W</i><span></span><i>A</i><i>S</i><i>D</i></div><button data-code-new>NEW DUNGEON</button></section>`);
  const api = createCanvasContext(stage); const cols = 17; const rows = 11; const tile = 54; let grid; let player; let bugs; let hazards; let portal; let health; let running = false;
  const randomMap = () => { grid = Array.from({ length: rows }, (_, y) => Array.from({ length: cols }, (_, x) => x === 0 || y === 0 || x === cols - 1 || y === rows - 1 || Math.random() < .12 ? 1 : 0)); player = { x: 1, y: 1 }; grid[1][1] = 0; portal = { x: cols - 2, y: rows - 2 }; grid[portal.y][portal.x] = 0; bugs = []; hazards = []; while (bugs.length < 5) { const p = { x: 1 + Math.floor(Math.random() * (cols - 2)), y: 1 + Math.floor(Math.random() * (rows - 2)) }; if (!grid[p.y][p.x] && (p.x !== 1 || p.y !== 1)) bugs.push(p); } while (hazards.length < 8) { const p = { x: 1 + Math.floor(Math.random() * (cols - 2)), y: 1 + Math.floor(Math.random() * (rows - 2)) }; if (!grid[p.y][p.x] && !bugs.some((b) => b.x === p.x && b.y === p.y)) hazards.push(p); } health = 3; update(); };
  const draw = () => { const { ctx, canvas } = api; ctx.fillStyle = "#070814"; ctx.fillRect(0, 0, canvas.width, canvas.height); const ox = (canvas.width - cols * tile) / 2; const oy = (canvas.height - rows * tile) / 2; for (let y = 0; y < rows; y += 1) for (let x = 0; x < cols; x += 1) { ctx.fillStyle = grid[y][x] ? "#1e1838" : (x + y) % 2 ? "#0d1222" : "#10172a"; ctx.fillRect(ox + x * tile, oy + y * tile, tile - 2, tile - 2); if (grid[y][x]) { ctx.strokeStyle = "rgba(182,140,255,.22)"; ctx.strokeRect(ox + x * tile + 7, oy + y * tile + 7, tile - 16, tile - 16); } } hazards.forEach((hazard) => { ctx.fillStyle = "#ff7fa8"; ctx.font = "800 26px monospace"; ctx.fillText("!", ox + hazard.x * tile + 20, oy + hazard.y * tile + 36); }); bugs.forEach((bug) => { ctx.fillStyle = "#ff5c6d"; ctx.beginPath(); ctx.arc(ox + bug.x * tile + tile / 2, oy + bug.y * tile + tile / 2, 13, 0, Math.PI * 2); ctx.fill(); ctx.fillStyle = "#070814"; ctx.font = "900 14px monospace"; ctx.fillText("×", ox + bug.x * tile + 21, oy + bug.y * tile + 32); }); ctx.fillStyle = bugs.length ? "#4c5266" : "#88f5a7"; ctx.fillRect(ox + portal.x * tile + 10, oy + portal.y * tile + 8, tile - 22, tile - 18); ctx.fillStyle = "#071019"; ctx.font = "900 10px monospace"; ctx.fillText("PROD", ox + portal.x * tile + 13, oy + portal.y * tile + 35); ctx.fillStyle = "#b68cff"; ctx.beginPath(); ctx.arc(ox + player.x * tile + tile / 2, oy + player.y * tile + tile / 2, 17, 0, Math.PI * 2); ctx.fill(); ctx.fillStyle = "#fff"; ctx.font = "900 13px monospace"; ctx.fillText("BM", ox + player.x * tile + 17, oy + player.y * tile + 31); };
  const update = () => { stage.querySelector("[data-bugs-left]").textContent = bugs.length; stage.querySelector("[data-code-health]").textContent = health; api.setScore((5 - bugs.length) * 200 + health * 50); draw(); };
  const move = (dx, dy) => { if (!running) return; const nx = player.x + dx; const ny = player.y + dy; if (grid[ny]?.[nx]) return; player = { x: nx, y: ny }; const bugIndex = bugs.findIndex((bug) => bug.x === nx && bug.y === ny); if (bugIndex >= 0) { bugs.splice(bugIndex, 1); api.addLog("Failing test collected and fixed."); } const hazardIndex = hazards.findIndex((hazard) => hazard.x === nx && hazard.y === ny); if (hazardIndex >= 0) { hazards.splice(hazardIndex, 1); health -= 1; api.addLog("Regression hit. Build health decreased."); } if (nx === portal.x && ny === portal.y) { if (!bugs.length) { running = false; api.setStatus("DEPLOYED"); api.showOverlay("PRODUCTION DEPLOYED", `You cleared the dungeon with ${health} build health remaining.`); } else api.addLog("Production is locked until every failing test is fixed."); } if (health <= 0) { running = false; api.setStatus("BUILD FAILED"); api.showOverlay("BUILD FAILED", "Too many regressions reached the branch. Try a safer route."); } update(); };
  const keyHandler = (event) => { const key = event.key.toLowerCase(); const movement = { arrowup: [0, -1], w: [0, -1], arrowdown: [0, 1], s: [0, 1], arrowleft: [-1, 0], a: [-1, 0], arrowright: [1, 0], d: [1, 0] }[key]; if (movement) { event.preventDefault(); move(...movement); } };
  window.addEventListener("keydown", keyHandler); const start = () => { randomMap(); running = true; api.hideOverlay(); api.setStatus("DEBUGGING"); api.addLog("Dungeon generated from a new project state."); }; stage.querySelector("[data-game-start]").addEventListener("click", start); stage.querySelector("[data-code-new]").addEventListener("click", start); randomMap(); return () => window.removeEventListener("keydown", keyHandler);
}

function setupDefense(stage) {
  const controls = stage.querySelector(".game-controls"); controls.insertAdjacentHTML("afterbegin", `<section class="defense-panel"><header>DEFENSE NETWORK</header><article><span>ORIGIN HEALTH</span><strong data-origin-health>100</strong></article><article><span>CACHE BUDGET</span><strong data-cache-budget>120</strong></article><article><span>WAVE</span><strong data-defense-wave>0/6</strong></article><button data-defense-next>NEXT WAVE</button><small>Cache node: 30 budget</small></section>`);
  const api = createCanvasContext(stage); const lanes = [170, 325, 480]; const sockets = []; lanes.forEach((y) => [260, 500, 740].forEach((x) => sockets.push({ x, y, tower: false, cooldown: 0 }))); let enemies = []; let bullets = []; let health = 100; let budget = 120; let wave = 0; let running = false; let frame;
  const draw = () => { const { ctx, canvas } = api; ctx.fillStyle = "#071019"; ctx.fillRect(0, 0, canvas.width, canvas.height); lanes.forEach((y) => { ctx.strokeStyle = "rgba(113,229,255,.16)"; ctx.lineWidth = 38; ctx.beginPath(); ctx.moveTo(40, y); ctx.lineTo(1040, y); ctx.stroke(); ctx.strokeStyle = "rgba(113,229,255,.42)"; ctx.lineWidth = 2; ctx.beginPath(); ctx.moveTo(40, y); ctx.lineTo(1040, y); ctx.stroke(); }); ctx.fillStyle = "#ff7fa8"; ctx.fillRect(1010, 120, 58, 410); ctx.fillStyle = "#071019"; ctx.font = "900 13px monospace"; ctx.save(); ctx.translate(1045, 320); ctx.rotate(Math.PI / 2); ctx.fillText("ORIGIN SERVER", -55, 0); ctx.restore(); sockets.forEach((socket) => { ctx.fillStyle = socket.tower ? "#71e5ff" : "rgba(255,255,255,.06)"; ctx.strokeStyle = socket.tower ? "#b7f3ff" : "rgba(255,255,255,.18)"; ctx.lineWidth = 2; ctx.beginPath(); ctx.arc(socket.x, socket.y, socket.tower ? 25 : 18, 0, Math.PI * 2); ctx.fill(); ctx.stroke(); if (socket.tower) { ctx.fillStyle = "#071019"; ctx.font = "900 12px monospace"; ctx.fillText("CDN", socket.x - 12, socket.y + 4); } }); enemies.forEach((enemy) => { ctx.fillStyle = enemy.health > 1 ? "#ff9a62" : "#ffd36e"; ctx.fillRect(enemy.x - 16, enemy.y - 13, 32, 26); ctx.fillStyle = "#071019"; ctx.font = "900 10px monospace"; ctx.fillText(String(enemy.health), enemy.x - 3, enemy.y + 4); }); bullets.forEach((bullet) => { ctx.fillStyle = "#d8ff72"; ctx.beginPath(); ctx.arc(bullet.x, bullet.y, 5, 0, Math.PI * 2); ctx.fill(); }); };
  const click = (event) => { if (!running) return; const rect = api.canvas.getBoundingClientRect(); const x = (event.clientX - rect.left) / rect.width * api.canvas.width; const y = (event.clientY - rect.top) / rect.height * api.canvas.height; const socket = sockets.find((item) => Math.hypot(item.x - x, item.y - y) < 34); if (socket && !socket.tower && budget >= 30) { socket.tower = true; budget -= 30; stage.querySelector("[data-cache-budget]").textContent = budget; api.addLog("Cache defense placed on request lane."); draw(); } };
  api.canvas.addEventListener("click", click);
  const spawnWave = () => { if (!running || enemies.length || wave >= 6) return; wave += 1; stage.querySelector("[data-defense-wave]").textContent = `${wave}/6`; for (let i = 0; i < 4 + wave * 2; i += 1) enemies.push({ x: -i * 68, y: lanes[i % lanes.length], health: 1 + Math.floor(wave / 2), speed: 1.1 + wave * .16 }); api.addLog(`Traffic storm wave ${wave} entered the edge.`); };
  stage.querySelector("[data-defense-next]").addEventListener("click", spawnWave);
  const loop = () => { if (!running) return; sockets.filter((socket) => socket.tower).forEach((socket) => { socket.cooldown -= 1; const target = enemies.find((enemy) => enemy.y === socket.y && enemy.x < socket.x + 190 && enemy.x > socket.x - 260); if (target && socket.cooldown <= 0) { bullets.push({ x: socket.x, y: socket.y, target, speed: 7 }); socket.cooldown = 35; } }); bullets.forEach((bullet) => { const dx = bullet.target.x - bullet.x; const dy = bullet.target.y - bullet.y; const distance = Math.hypot(dx, dy); bullet.x += dx / distance * bullet.speed; bullet.y += dy / distance * bullet.speed; if (distance < 12) { bullet.target.health -= 1; bullet.hit = true; } }); bullets = bullets.filter((bullet) => !bullet.hit && bullet.target.health > 0); enemies = enemies.filter((enemy) => { if (enemy.health <= 0) { budget += 6; return false; } enemy.x += enemy.speed; if (enemy.x >= 1000) { health -= 7; return false; } return true; }); stage.querySelector("[data-origin-health]").textContent = health; stage.querySelector("[data-cache-budget]").textContent = budget; api.setScore((wave - 1) * 500 + budget + health * 2); if (health <= 0) { running = false; api.setStatus("ORIGIN DOWN"); api.showOverlay("ORIGIN OVERLOADED", `You reached wave ${wave}. Spread cache defenses across all three request lanes.`); } else if (wave === 6 && !enemies.length) { running = false; api.setStatus("DEFENDED"); api.showOverlay("NETWORK DEFENDED", `All six traffic waves were absorbed with ${health} origin health remaining.`); } draw(); frame = requestAnimationFrame(loop); };
  const start = () => { cancelAnimationFrame(frame); sockets.forEach((socket) => { socket.tower = false; socket.cooldown = 0; }); enemies = []; bullets = []; health = 100; budget = 120; wave = 0; running = true; stage.querySelector("[data-origin-health]").textContent = health; stage.querySelector("[data-cache-budget]").textContent = budget; stage.querySelector("[data-defense-wave]").textContent = "0/6"; api.hideOverlay(); api.setStatus("DEFENDING"); spawnWave(); frame = requestAnimationFrame(loop); };
  stage.querySelector("[data-game-start]").addEventListener("click", start); draw(); return () => { cancelAnimationFrame(frame); api.canvas.removeEventListener("click", click); };
}

function setupEvolution(stage) {
  const controls = stage.querySelector(".game-controls"); controls.insertAdjacentHTML("afterbegin", `<section class="evolution-panel"><header>EVOLUTION PRESSURE</header><label>Mutation <output data-mutation-output>12%</output><input type="range" min="0" max="40" value="12" data-mutation></label><label>Simulation speed <output data-evo-speed-output>1×</output><input type="range" min="1" max="6" value="1" data-evo-speed></label><article><span>GENERATION</span><strong data-generation>1</strong></article><article><span>POPULATION</span><strong data-population>0</strong></article><article><span>BEST FITNESS</span><strong data-fitness>0</strong></article><button data-add-food>ADD FOOD</button></section>`);
  const api = createCanvasContext(stage); let organisms = []; let food = []; let generation = 1; let bestFitness = 0; let running = false; let frame; const mutation = stage.querySelector("[data-mutation]"); const speed = stage.querySelector("[data-evo-speed]"); mutation.addEventListener("input", () => stage.querySelector("[data-mutation-output]").textContent = `${mutation.value}%`); speed.addEventListener("input", () => stage.querySelector("[data-evo-speed-output]").textContent = `${speed.value}×`);
  const makeOrganism = (parent) => { const mutate = () => (Math.random() - .5) * Number(mutation.value) / 100; return { x: parent?.x ?? Math.random() * api.canvas.width, y: parent?.y ?? Math.random() * api.canvas.height, angle: Math.random() * Math.PI * 2, speed: Math.max(.3, (parent?.speed ?? (1 + Math.random())) * (1 + mutate())), sense: Math.max(20, (parent?.sense ?? (70 + Math.random() * 90)) * (1 + mutate())), energy: 110, age: 0, eaten: 0, hue: (parent?.hue ?? Math.random() * 360) + mutate() * 100 }; };
  const seed = () => { organisms = Array.from({ length: 24 }, () => makeOrganism()); food = Array.from({ length: 95 }, () => ({ x: Math.random() * api.canvas.width, y: Math.random() * api.canvas.height })); generation = 1; bestFitness = 0; };
  const addFood = (count = 28) => { for (let i = 0; i < count; i += 1) food.push({ x: Math.random() * api.canvas.width, y: Math.random() * api.canvas.height }); };
  stage.querySelector("[data-add-food]").addEventListener("click", () => { addFood(); api.addLog("Additional energy introduced into the ecosystem."); });
  const update = () => { const steps = Number(speed.value); for (let step = 0; step < steps; step += 1) { organisms.forEach((organism) => { organism.age += 1; organism.energy -= .08 + organism.speed * .018; let target = null; let best = organism.sense; food.forEach((item) => { const distance = Math.hypot(item.x - organism.x, item.y - organism.y); if (distance < best) { best = distance; target = item; } }); if (target) organism.angle = Math.atan2(target.y - organism.y, target.x - organism.x); else organism.angle += (Math.random() - .5) * .22; organism.x = (organism.x + Math.cos(organism.angle) * organism.speed + api.canvas.width) % api.canvas.width; organism.y = (organism.y + Math.sin(organism.angle) * organism.speed + api.canvas.height) % api.canvas.height; const foodIndex = food.findIndex((item) => Math.hypot(item.x - organism.x, item.y - organism.y) < 9); if (foodIndex >= 0) { food.splice(foodIndex, 1); organism.energy += 38; organism.eaten += 1; if (organism.energy > 170 && organisms.length < 80) { organism.energy *= .55; organisms.push(makeOrganism(organism)); } } }); organisms = organisms.filter((organism) => organism.energy > 0 && organism.age < 5200); if (Math.random() < .12) addFood(1); if (organisms.length < 8) { const survivors = [...organisms].sort((a, b) => b.eaten - a.eaten).slice(0, 4); const parents = survivors.length ? survivors : Array.from({ length: 4 }, () => makeOrganism()); bestFitness = Math.max(bestFitness, ...parents.map((item) => item.eaten)); generation += 1; organisms = Array.from({ length: 26 }, (_, index) => makeOrganism(parents[index % parents.length])); addFood(80); api.addLog(`Generation ${generation} began from the strongest surviving traits.`); } } };
  const draw = () => { const { ctx, canvas } = api; ctx.fillStyle = "#06110f"; ctx.fillRect(0, 0, canvas.width, canvas.height); ctx.fillStyle = "rgba(136,245,167,.55)"; food.forEach((item) => { ctx.beginPath(); ctx.arc(item.x, item.y, 3, 0, Math.PI * 2); ctx.fill(); }); organisms.forEach((organism) => { ctx.strokeStyle = `hsla(${organism.hue}, 80%, 68%, .08)`; ctx.beginPath(); ctx.arc(organism.x, organism.y, organism.sense, 0, Math.PI * 2); ctx.stroke(); ctx.save(); ctx.translate(organism.x, organism.y); ctx.rotate(organism.angle); ctx.fillStyle = `hsl(${organism.hue}, 80%, 62%)`; ctx.beginPath(); ctx.moveTo(10, 0); ctx.lineTo(-7, -6); ctx.lineTo(-4, 0); ctx.lineTo(-7, 6); ctx.closePath(); ctx.fill(); ctx.restore(); }); stage.querySelector("[data-generation]").textContent = generation; stage.querySelector("[data-population]").textContent = organisms.length; stage.querySelector("[data-fitness]").textContent = Math.max(bestFitness, ...organisms.map((item) => item.eaten)); api.setScore(generation * 100 + organisms.length); };
  const loop = () => { if (!running) return; update(); draw(); frame = requestAnimationFrame(loop); };
  const start = () => { cancelAnimationFrame(frame); seed(); running = true; api.hideOverlay(); api.setStatus("EVOLVING"); frame = requestAnimationFrame(loop); };
  stage.querySelector("[data-game-start]").addEventListener("click", start); seed(); draw(); return () => cancelAnimationFrame(frame);
}

function setupLogistics(stage) {
  const controls = stage.querySelector(".game-controls"); controls.insertAdjacentHTML("afterbegin", `<section class="logistics-panel"><header>FLEET CONTROL</header><article><span>CASH</span><strong data-logistics-cash>$2,500</strong></article><article><span>REPUTATION</span><strong data-logistics-rep>100</strong></article><article><span>DAY</span><strong data-logistics-day>1/12</strong></article><button data-logistics-next>ADVANCE DAY</button></section><section class="fleet-list" data-fleet-list></section><section class="job-list" data-job-list></section>`);
  const api = createCanvasContext(stage); const towns = [{ name: "Davis", x: 165, y: 190 }, { name: "Freeport", x: 420, y: 120 }, { name: "Rockford", x: 720, y: 220 }, { name: "Beloit", x: 610, y: 430 }, { name: "Janesville", x: 880, y: 490 }, { name: "Monroe", x: 290, y: 475 }]; let trucks; let jobs; let cash; let reputation; let day; let running = false;
  const generateJobs = () => { jobs = Array.from({ length: 4 }, (_, index) => { const from = towns[Math.floor(Math.random() * towns.length)]; let to = towns[Math.floor(Math.random() * towns.length)]; while (to === from) to = towns[Math.floor(Math.random() * towns.length)]; const distance = Math.round(Math.hypot(to.x - from.x, to.y - from.y) / 3); return { id: `${day}-${index}`, from, to, distance, pay: 280 + distance * 3, deadline: day + 2 + Math.floor(Math.random() * 3), assigned: null }; }); };
  const renderLists = () => { stage.querySelector("[data-fleet-list]").innerHTML = `<header>FLEET</header>${trucks.map((truck, index) => `<article class="${truck.busy > 0 ? "busy" : "available"}"><span>T${index + 1}</span><p><strong>${truck.name}</strong><small>${truck.busy > 0 ? `Busy ${truck.busy}d` : `${truck.fuel}% fuel`}</small></p><b>${truck.capacity}T</b></article>`).join("")}`; stage.querySelector("[data-job-list]").innerHTML = `<header>OPEN CONTRACTS</header>${jobs.map((job, index) => `<button data-job-index="${index}" ${job.assigned !== null ? "disabled" : ""}><span>${job.from.name} → ${job.to.name}</span><strong>$${job.pay}</strong><small>${job.distance} mi • due day ${job.deadline}</small></button>`).join("")}`; stage.querySelectorAll("[data-job-index]").forEach((button) => button.addEventListener("click", () => assignJob(Number(button.dataset.jobIndex)))); stage.querySelector("[data-logistics-cash]").textContent = `$${Math.round(cash).toLocaleString()}`; stage.querySelector("[data-logistics-rep]").textContent = reputation; stage.querySelector("[data-logistics-day]").textContent = `${day}/12`; api.setScore(cash + reputation * 20); };
  const assignJob = (jobIndex) => { const truckIndex = trucks.findIndex((truck) => truck.busy <= 0 && truck.fuel > jobs[jobIndex].distance / 5); if (truckIndex < 0) { api.addLog("No available truck has enough fuel for that contract."); return; } const job = jobs[jobIndex]; job.assigned = truckIndex; trucks[truckIndex].busy = Math.max(1, Math.ceil(job.distance / 180)); trucks[truckIndex].fuel -= Math.round(job.distance / 5); trucks[truckIndex].pay = job.pay; trucks[truckIndex].deadline = job.deadline; api.addLog(`${trucks[truckIndex].name} assigned ${job.from.name} to ${job.to.name}.`); renderLists(); draw(); };
  const draw = () => { const { ctx, canvas } = api; ctx.fillStyle = "#0d1115"; ctx.fillRect(0, 0, canvas.width, canvas.height); ctx.strokeStyle = "rgba(255,154,98,.24)"; ctx.lineWidth = 3; towns.forEach((town, index) => towns.slice(index + 1).forEach((other) => { if (Math.hypot(town.x - other.x, town.y - other.y) < 430) { ctx.beginPath(); ctx.moveTo(town.x, town.y); ctx.lineTo(other.x, other.y); ctx.stroke(); } })); jobs.forEach((job) => { ctx.strokeStyle = job.assigned !== null ? "#ff9a62" : "rgba(255,255,255,.12)"; ctx.lineWidth = job.assigned !== null ? 6 : 2; ctx.beginPath(); ctx.moveTo(job.from.x, job.from.y); ctx.lineTo(job.to.x, job.to.y); ctx.stroke(); }); towns.forEach((town) => { ctx.fillStyle = "#ff9a62"; ctx.beginPath(); ctx.arc(town.x, town.y, 17, 0, Math.PI * 2); ctx.fill(); ctx.fillStyle = "#f4f8fb"; ctx.font = "800 17px sans-serif"; ctx.fillText(town.name, town.x + 25, town.y + 6); }); ctx.fillStyle = "#91a4b4"; ctx.font = "15px monospace"; ctx.fillText("SIMULATED REGIONAL OPERATIONS MAP", 45, 600); };
  const advance = () => { if (!running) return; day += 1; trucks.forEach((truck) => { if (truck.busy > 0) { truck.busy -= 1; if (truck.busy === 0 && truck.pay) { cash += truck.pay; if (day > truck.deadline) reputation -= 8; else reputation = Math.min(100, reputation + 2); api.addLog(`${truck.name} completed a contract for $${truck.pay}.`); truck.pay = 0; } } else { truck.fuel = Math.min(100, truck.fuel + 18); cash -= 22; } }); jobs.filter((job) => job.assigned === null && day > job.deadline).forEach(() => { reputation -= 4; }); if (day > 12) { running = false; api.setStatus(reputation >= 70 ? "PROFITABLE" : "CONTRACT RISK"); api.showOverlay("TWELVE-DAY RUN COMPLETE", `Final cash: $${Math.round(cash).toLocaleString()} with ${reputation} reputation.`); return; } generateJobs(); renderLists(); draw(); };
  stage.querySelector("[data-logistics-next]").addEventListener("click", advance);
  const start = () => { trucks = [{ name: "PCS 01", fuel: 100, capacity: 8, busy: 0 }, { name: "PCS 02", fuel: 86, capacity: 12, busy: 0 }, { name: "PCS 03", fuel: 74, capacity: 18, busy: 0 }]; cash = 2500; reputation = 100; day = 1; running = true; generateJobs(); renderLists(); draw(); api.hideOverlay(); api.setStatus("DISPATCHING"); };
  stage.querySelector("[data-game-start]").addEventListener("click", start); trucks = []; jobs = []; cash = 2500; reputation = 100; day = 1; draw(); return () => {};
}

function controlsFor(id) {
  return "";
}

export function createBrowserGame({ stage, demo, onReady }) {
  const config = GAME_CONFIG[demo.id];
  stage.innerHTML = gameShell(config, controlsFor(demo.id));
  let cleanup;
  if (demo.id === "cloud-ops-crisis") cleanup = setupCloudOps(stage);
  else if (demo.id === "golf-challenge") cleanup = setupGolf(stage);
  else if (demo.id === "code-dungeon") cleanup = setupCodeDungeon(stage);
  else if (demo.id === "data-center-defense") cleanup = setupDefense(stage);
  else if (demo.id === "digital-evolution") cleanup = setupEvolution(stage);
  else cleanup = setupLogistics(stage);
  onReady?.({ engineType: "CANVAS GAME" });
  return { dispose() { cleanup?.(); stage.replaceChildren(); }, getStats() { return { fps: "60", meshes: stage.querySelectorAll("button, canvas, article").length }; }, setGuidedOrbit() {}, resetCamera() { stage.querySelector("[data-game-start]")?.click(); } };
}
