const $=(r,s)=>r.querySelector(s);const $$=(r,s)=>[...r.querySelectorAll(s)];
function overlay(title,copy){return `<div class="game-overlay" data-game-overlay><strong>${title}</strong><p>${copy}</p><button data-game-start>START</button></div>`;}
function ctl(stage,cleanup,reset,stats){return{dispose(){cleanup?.();stage.replaceChildren();},getStats(){return stats?.()||{fps:"60",meshes:stage.querySelectorAll("*").length};},setGuidedOrbit(){},resetCamera(){reset?.();}};}
function resizeCanvas(canvas){const rect=canvas.getBoundingClientRect();const ratio=Math.min(2,window.devicePixelRatio||1);if(canvas.width!==Math.floor(rect.width*ratio)||canvas.height!==Math.floor(rect.height*ratio)){canvas.width=Math.floor(rect.width*ratio);canvas.height=Math.floor(rect.height*ratio);return ratio;}return ratio;}

function createCloudOps({stage,onReady}){
  let timer,elapsed=0,traffic=62,capacity=100,budget=120,uptime=100,incident=null,running=false,score=0;
  stage.innerHTML=`<section class="demo-surface game-cloud-ops"><header><div><span>ON-CALL STRATEGY</span><h2>Cloud Ops Crisis</h2></div><div class="ops-clock"><strong data-shift>00:00</strong><small>SHIFT TIME</small></div></header><div class="ops-game"><main><div class="traffic-chart"><canvas data-traffic-chart></canvas><div><span>LIVE TRAFFIC</span><strong data-traffic>62 RPS</strong><small data-capacity>100 RPS capacity</small></div></div><div class="service-rack">${["EDGE","CACHE","API","QUEUE","DATABASE"].map((n,i)=>`<article data-service="${i}" class="${i===1?"disabled":"healthy"}"><i></i><strong>${n}</strong><small>${i===1?"NOT DEPLOYED":"HEALTHY"}</small><meter min="0" max="100" value="100"></meter></article>`).join("")}</div><section class="incident-desk"><header><span>INCIDENT DESK</span><strong data-incident-count>0 active</strong></header><div data-incidents><p>No active incidents. Traffic is rising.</p></div></section></main><aside><div class="ops-score"><article><span>UPTIME</span><strong data-uptime>100.0%</strong></article><article><span>BUDGET</span><strong data-budget>$120</strong></article><article><span>SCORE</span><strong data-game-score>0</strong></article><article><span>STATUS</span><strong data-game-status>READY</strong></article></div><h3>OPERATIONS</h3><button data-op="scale">Scale API +50 RPS <em>$18</em></button><button data-op="cache">Deploy cache <em>$25</em></button><button data-op="queue">Enable queue <em>$20</em></button><button data-op="repair">Repair active incident <em>$14</em></button><div class="ops-log"><h3>SHIFT LOG</h3><ol data-log><li>System ready.</li></ol></div></aside>${overlay("Cloud Ops Crisis","Keep uptime above 70% for a 90-second shift. Traffic, incidents, budget, and architecture all matter.")}</div></section>`;
  const canvas=$(stage,"[data-traffic-chart]"),ctx=canvas.getContext("2d"),history=Array(70).fill(traffic);
  function draw(){const ratio=resizeCanvas(canvas),w=canvas.width,h=canvas.height;ctx.clearRect(0,0,w,h);ctx.fillStyle="#07131d";ctx.fillRect(0,0,w,h);ctx.strokeStyle="rgba(113,229,255,.12)";for(let i=1;i<5;i++){ctx.beginPath();ctx.moveTo(0,h*i/5);ctx.lineTo(w,h*i/5);ctx.stroke();}ctx.beginPath();history.forEach((v,i)=>{const x=i/(history.length-1)*w,y=h-(v/300)*h;i?ctx.lineTo(x,y):ctx.moveTo(x,y);});ctx.strokeStyle=traffic>capacity?"#ff7468":"#71e5ff";ctx.lineWidth=3*ratio;ctx.stroke();ctx.beginPath();ctx.moveTo(0,h-(capacity/300)*h);ctx.lineTo(w,h-(capacity/300)*h);ctx.strokeStyle="#ffd36e";ctx.setLineDash([8*ratio,8*ratio]);ctx.stroke();ctx.setLineDash([]);}
  function addLog(text){$(stage,"[data-log]").insertAdjacentHTML("afterbegin",`<li>${text}</li>`);while($(stage,"[data-log]").children.length>7)$(stage,"[data-log]").lastElementChild.remove();}
  function render(){history.push(traffic);history.shift();$(stage,"[data-traffic]").textContent=`${Math.round(traffic)} RPS`;$(stage,"[data-capacity]").textContent=`${capacity} RPS capacity`;$(stage,"[data-uptime]").textContent=`${uptime.toFixed(1)}%`;$(stage,"[data-budget]").textContent=`$${Math.round(budget)}`;$(stage,"[data-game-score]").textContent=Math.round(score);$(stage,"[data-shift]").textContent=`${String(Math.floor(elapsed/60)).padStart(2,"0")}:${String(Math.floor(elapsed%60)).padStart(2,"0")}`;$(stage,"[data-incident-count]").textContent=incident?"1 active":"0 active";$(stage,"[data-incidents]").innerHTML=incident?`<article class="incident-card"><span>SEV-${incident.severity}</span><strong>${incident.name}</strong><p>${incident.copy}</p><meter min="0" max="100" value="${incident.progress}"></meter></article>`:"<p>No active incidents. Traffic is rising.</p>";draw();}
  function tick(){if(!running)return;elapsed+=.5;traffic+=1.2+elapsed*.012;budget+=.45;if(Math.random()<.018&&!incident){incident={severity:Math.random()>.55?2:3,name:["Database throttling","Provider latency","Retry storm"][Math.floor(Math.random()*3)],copy:"Unresolved impact is reducing uptime.",progress:10};addLog(`Incident opened: ${incident.name}.`);}if(incident)incident.progress=Math.min(100,incident.progress+2);const overload=Math.max(0,traffic-capacity);uptime-=overload*.004+(incident?.severity||0)*.025;uptime=Math.min(100,uptime+.03);score+=uptime*.08;if(uptime<70||elapsed>=90){running=false;clearInterval(timer);$(stage,"[data-game-status]").textContent=uptime<70?"OUTAGE":"SHIFT COMPLETE";const o=$(stage,"[data-game-overlay]");o.hidden=false;o.querySelector("strong").textContent=uptime<70?"SERVICE OUTAGE":"SHIFT COMPLETE";o.querySelector("p").textContent=`Final score ${Math.round(score)} with ${uptime.toFixed(1)}% uptime.`;o.querySelector("button").textContent="PLAY AGAIN";}render();}
  $$(stage,"[data-op]").forEach(b=>b.addEventListener("click",()=>{const a=b.dataset.op;if(a==="scale"&&budget>=18){budget-=18;capacity+=50;addLog("API capacity increased.");}if(a==="cache"&&budget>=25){budget-=25;traffic*=.82;const n=$(stage,'[data-service="1"]');n.className="healthy";n.querySelector("small").textContent="ACTIVE";b.disabled=true;addLog("Cache deployed; origin load reduced.");}if(a==="queue"&&budget>=20){budget-=20;capacity+=25;const n=$(stage,'[data-service="3"]');n.className="healthy";n.querySelector("small").textContent="BUFFERING";b.disabled=true;addLog("Queue enabled; spikes are buffered.");}if(a==="repair"&&budget>=14&&incident){budget-=14;addLog(`Resolved ${incident.name}.`);incident=null;}render();}));
  function start(){clearInterval(timer);elapsed=0;traffic=62;capacity=100;budget=120;uptime=100;incident=null;score=0;running=true;$(stage,"[data-game-overlay]").hidden=true;$(stage,"[data-game-status]").textContent="LIVE";$$(stage,"[data-op]").forEach(b=>b.disabled=false);timer=setInterval(tick,500);render();}
  $(stage,"[data-game-start]").addEventListener("click",start);render();onReady?.({engineType:"OPS STRATEGY ENGINE"});return ctl(stage,()=>clearInterval(timer),start,()=>({fps:"60",meshes:5+(incident?1:0)}));
}

function createGolf({stage,onReady}){
  let frame,running=false,ball,shots=3,score=0,wind=0,last=0;
  stage.innerHTML=`<section class="demo-surface game-golf"><header><div><span>BRADLEY'S FAIRWAY</span><h2>Target Golf</h2></div><div class="golf-score"><strong data-game-score>0</strong><small>ROUND SCORE</small><b data-game-status>READY</b></div></header><div class="golf-layout"><main><canvas data-golf-canvas></canvas>${overlay("Fairway Target Challenge","Three shots. Read the wind, choose a club, shape the launch, and land close to the 165-yard pin.")}</main><aside><h3>SHOT SETUP</h3><label>Club<select data-club><option value="180">7 Iron</option><option value="145">9 Iron</option><option value="105">Wedge</option></select></label><label>Launch angle <output data-angle-out>42°</output><input data-angle type="range" min="24" max="62" value="42"></label><label>Power <output data-power-out>78%</output><input data-power type="range" min="30" max="100" value="78"></label><div class="wind-card"><span>WIND</span><strong data-wind>--</strong><i data-wind-arrow>→</i></div><div class="shots"><span>SHOTS LEFT</span><strong data-shots>3</strong></div><button data-swing>SWING</button><ol data-shot-log><li>Round ready.</li></ol></aside></div></section>`;
  const canvas=$(stage,"[data-golf-canvas]"),ctx=canvas.getContext("2d"),angle=$(stage,"[data-angle]"),power=$(stage,"[data-power]");angle.addEventListener("input",()=>$(stage,"[data-angle-out]").textContent=`${angle.value}°`);power.addEventListener("input",()=>$(stage,"[data-power-out]").textContent=`${power.value}%`);
  function resetBall(){ball={x:.09,y:.78,vx:0,vy:0,z:0,vz:0,flying:false,trail:[]};}
  function draw(){const r=resizeCanvas(canvas),w=canvas.width,h=canvas.height;ctx.clearRect(0,0,w,h);const sky=ctx.createLinearGradient(0,0,0,h);sky.addColorStop(0,"#87c9ef");sky.addColorStop(.52,"#d9eff8");sky.addColorStop(.53,"#5e9a45");sky.addColorStop(1,"#244d31");ctx.fillStyle=sky;ctx.fillRect(0,0,w,h);ctx.fillStyle="#477d37";ctx.beginPath();ctx.moveTo(0,h*.76);ctx.quadraticCurveTo(w*.45,h*.61,w,h*.73);ctx.lineTo(w,h);ctx.lineTo(0,h);ctx.fill();ctx.fillStyle="#8bc563";ctx.beginPath();ctx.ellipse(w*.79,h*.7,w*.13,h*.055,0,0,Math.PI*2);ctx.fill();[.025,.055,.095].forEach((rad,i)=>{ctx.strokeStyle=["#fff","rgba(255,255,255,.55)","rgba(255,255,255,.25)"][i];ctx.lineWidth=2*r;ctx.beginPath();ctx.ellipse(w*.79,h*.7,w*rad,h*rad*.42,0,0,Math.PI*2);ctx.stroke();});ctx.strokeStyle="#fff";ctx.lineWidth=3*r;ctx.beginPath();ctx.moveTo(w*.79,h*.7);ctx.lineTo(w*.79,h*.43);ctx.stroke();ctx.fillStyle="#d8ff72";ctx.beginPath();ctx.moveTo(w*.79,h*.43);ctx.lineTo(w*.85,h*.455);ctx.lineTo(w*.79,h*.49);ctx.fill();if(ball.trail.length>1){ctx.strokeStyle="rgba(255,255,255,.55)";ctx.lineWidth=2*r;ctx.beginPath();ball.trail.forEach((p,i)=>{const x=p.x*w,y=(p.y-p.z*.45)*h;i?ctx.lineTo(x,y):ctx.moveTo(x,y);});ctx.stroke();}ctx.fillStyle="#fff";ctx.beginPath();ctx.arc(ball.x*w,(ball.y-ball.z*.45)*h,8*r*(1+ball.z*.3),0,Math.PI*2);ctx.fill();ctx.fillStyle="rgba(0,0,0,.22)";ctx.beginPath();ctx.ellipse(ball.x*w,ball.y*h,11*r,4*r,0,0,Math.PI*2);ctx.fill();ctx.fillStyle="#173525";ctx.font=`${16*r}px sans-serif`;ctx.fillText("165 YARDS",w*.74,h*.79);}
  function loop(t){if(!running)return;const dt=Math.min(.025,(t-last)/1000||0);last=t;if(ball.flying){ball.vz-=1.25*dt;ball.x+=ball.vx*dt;ball.y+=ball.vy*dt;ball.z+=ball.vz*dt;ball.vx+=wind*.0002*dt;ball.trail.push({...ball});if(ball.z<=0&&ball.vz<0){ball.z=0;ball.flying=false;const dx=(ball.x-.79)*165,dy=(ball.y-.70)*165;const dist=Math.hypot(dx,dy);const points=Math.max(0,Math.round(1000-dist*18));score+=points;$(stage,"[data-game-score]").textContent=score;$(stage,"[data-shot-log]").insertAdjacentHTML("afterbegin",`<li>${points} points • ${dist.toFixed(1)} yards from pin</li>`);if(shots<=0){running=false;$(stage,"[data-game-status]").textContent="ROUND COMPLETE";const o=$(stage,"[data-game-overlay]");o.hidden=false;o.querySelector("strong").textContent="ROUND COMPLETE";o.querySelector("p").textContent=`Final score: ${score}.`;o.querySelector("button").textContent="PLAY AGAIN";}else setTimeout(resetBall,500);}}draw();frame=requestAnimationFrame(loop);}
  $(stage,"[data-swing]").addEventListener("click",()=>{if(!running||ball.flying||shots<=0)return;shots--;$(stage,"[data-shots]").textContent=shots;const a=Number(angle.value)*Math.PI/180,p=Number(power.value)/100,range=Number($(stage,"[data-club]").value)/165;ball.vx=Math.cos(a)*range*p*.72;ball.vy=-wind*.002;ball.vz=Math.sin(a)*range*p*1.3;ball.flying=true;});
  function start(){cancelAnimationFrame(frame);shots=3;score=0;wind=(Math.random()*14-7);$(stage,"[data-wind]").textContent=`${Math.abs(wind).toFixed(1)} mph ${wind<0?"W":"E"}`;$(stage,"[data-wind-arrow]").style.transform=`rotate(${wind<0?180:0}deg)`;$(stage,"[data-shots]").textContent=shots;$(stage,"[data-game-score]").textContent=0;$(stage,"[data-game-status]").textContent="PLAYING";$(stage,"[data-game-overlay]").hidden=true;resetBall();running=true;last=performance.now();frame=requestAnimationFrame(loop);}
  $(stage,"[data-game-start]").addEventListener("click",start);resetBall();draw();onReady?.({engineType:"PROJECTILE PHYSICS"});return ctl(stage,()=>cancelAnimationFrame(frame),start,()=>({fps:"60",meshes:ball.trail.length}));
}

function createDungeon({stage,onReady}){
  const map=["####################","#P....#......#.....D#","#.##..#.####.#.###..#","#..B..#....#.#...#..#","###.######.#.###.#.##","#...#....#.#.....#..#","#.###.B..#.#####.##.#","#.....##.#.....#....#","#.#####..####B.####.#","#.................X.#","####################"];
  let frame,running=false,player={x:1,y:1},bugs=new Set(),keys={};
  stage.innerHTML=`<section class="demo-surface game-dungeon"><header><div><span>SOFTWARE ROGUELIKE</span><h2>Code Dungeon</h2></div><div><strong data-game-score>0 / 3 BUGS</strong><b data-game-status>READY</b></div></header><div class="dungeon-layout"><main><canvas data-dungeon-canvas tabindex="0"></canvas>${overlay("Code Dungeon","Explore with WASD or arrows. Collect all three failing tests, avoid regressions, then reach the production portal.")}</main><aside><h3>BUILD STATUS</h3><div class="dungeon-legend"><span><i class="player"></i>Developer</span><span><i class="bug"></i>Failing test</span><span><i class="hazard"></i>Regression</span><span><i class="portal"></i>Production</span></div><article><span>HEALTH</span><strong data-health>3</strong></article><article><span>TESTS FIXED</span><strong data-fixed>0</strong></article><ol data-dungeon-log><li>Dungeon ready.</li></ol><div class="touch-pad"><button data-move="up">↑</button><button data-move="left">←</button><button data-move="down">↓</button><button data-move="right">→</button></div></aside></div></section>`;
  const canvas=$(stage,"[data-dungeon-canvas]"),ctx=canvas.getContext("2d");let health=3,fixed=0;
  function reset(){player={x:1,y:1};health=3;fixed=0;bugs=new Set();map.forEach((row,y)=>[...row].forEach((c,x)=>{if(c==="B")bugs.add(`${x},${y}`);}));}
  function tile(x,y){return map[y]?.[x]||"#";}function move(dx,dy){if(!running)return;const nx=player.x+dx,ny=player.y+dy,c=tile(nx,ny);if(c==="#")return;player={x:nx,y:ny};const key=`${nx},${ny}`;if(bugs.has(key)){bugs.delete(key);fixed++;$(stage,"[data-dungeon-log]").insertAdjacentHTML("afterbegin","<li>Failing test fixed.</li>");}if(c==="X"){health--;$(stage,"[data-dungeon-log]").insertAdjacentHTML("afterbegin","<li>Regression hit. Health lost.</li>");}if(c==="D"&&fixed===3)end(true);if(health<=0)end(false);update();draw();}
  function update(){$(stage,"[data-health]").textContent=health;$(stage,"[data-fixed]").textContent=fixed;$(stage,"[data-game-score]").textContent=`${fixed} / 3 BUGS`;}
  function draw(){const r=resizeCanvas(canvas),w=canvas.width,h=canvas.height,cw=w/map[0].length,ch=h/map.length;ctx.fillStyle="#090713";ctx.fillRect(0,0,w,h);map.forEach((row,y)=>[...row].forEach((c,x)=>{const px=x*cw,py=y*ch;if(c==="#"){ctx.fillStyle="#251f3c";ctx.fillRect(px,py,cw,ch);ctx.strokeStyle="#5a4d8d";ctx.strokeRect(px,py,cw,ch);}else{ctx.fillStyle=(x+y)%2?"#100d1e":"#151126";ctx.fillRect(px,py,cw,ch);}if(c==="D"){ctx.fillStyle=fixed===3?"#88f5a7":"#394b46";ctx.fillRect(px+cw*.25,py+ch*.15,cw*.5,ch*.7);}if(c==="X"){ctx.fillStyle="#ff5577";ctx.beginPath();ctx.moveTo(px+cw*.5,py+ch*.15);ctx.lineTo(px+cw*.85,py+ch*.8);ctx.lineTo(px+cw*.15,py+ch*.8);ctx.fill();}if(c==="B"&&bugs.has(`${x},${y}`)){ctx.fillStyle="#ff9a62";ctx.beginPath();ctx.arc(px+cw*.5,py+ch*.5,Math.min(cw,ch)*.23,0,Math.PI*2);ctx.fill();}}));ctx.fillStyle="#b68cff";ctx.beginPath();ctx.arc((player.x+.5)*cw,(player.y+.5)*ch,Math.min(cw,ch)*.28,0,Math.PI*2);ctx.fill();ctx.fillStyle="#fff";ctx.font=`${Math.min(cw,ch)*.28}px monospace`;ctx.textAlign="center";ctx.fillText("BM",(player.x+.5)*cw,(player.y+.58)*ch);}
  function end(win){running=false;$(stage,"[data-game-status]").textContent=win?"DEPLOYED":"BUILD FAILED";const o=$(stage,"[data-game-overlay]");o.hidden=false;o.querySelector("strong").textContent=win?"PRODUCTION UNLOCKED":"BUILD FAILED";o.querySelector("p").textContent=win?"All failing tests were fixed before deployment.":"Regressions exhausted your health.";o.querySelector("button").textContent="PLAY AGAIN";}
  function start(){reset();running=true;$(stage,"[data-game-overlay]").hidden=true;$(stage,"[data-game-status]").textContent="EXPLORING";update();draw();canvas.focus();}
  window.addEventListener("keydown",keyHandler);function keyHandler(e){if(["ArrowUp","w","W"].includes(e.key))move(0,-1);if(["ArrowDown","s","S"].includes(e.key))move(0,1);if(["ArrowLeft","a","A"].includes(e.key))move(-1,0);if(["ArrowRight","d","D"].includes(e.key))move(1,0);}$$(stage,"[data-move]").forEach(b=>b.addEventListener("click",()=>move(...({up:[0,-1],down:[0,1],left:[-1,0],right:[1,0]})[b.dataset.move])));$(stage,"[data-game-start]").addEventListener("click",start);reset();draw();onReady?.({engineType:"TILE COLLISION ENGINE"});return ctl(stage,()=>window.removeEventListener("keydown",keyHandler),start,()=>({fps:"60",meshes:bugs.size+1}));
}

function createDefense({stage,onReady}){
  let frame,running=false,last=0,wave=0,credits=100,lives=10,score=0,enemies=[],towers=[],projectiles=[],spawnTimer=0,toSpawn=0;
  stage.innerHTML=`<section class="demo-surface game-defense"><header><div><span>NETWORK TOWER DEFENSE</span><h2>Data Center Defense</h2></div><div class="defense-stats"><span>WAVE <strong data-wave>0 / 6</strong></span><span>CREDITS <strong data-credits>100</strong></span><span>ORIGIN <strong data-lives>10</strong></span><span>SCORE <strong data-game-score>0</strong></span><b data-game-status>READY</b></div></header><div class="defense-layout"><main><canvas data-defense-canvas></canvas>${overlay("Data Center Defense","Place cache towers in open sockets. Each tower intercepts traffic bots before they overload the origin server.")}</main><aside><h3>CACHE TOWERS</h3><button data-tower="edge"><i>◎</i><span><strong>Edge Cache</strong><small>Fast • short range</small></span><em>30</em></button><button data-tower="shield"><i>◇</i><span><strong>Shield Cache</strong><small>Slow • heavy damage</small></span><em>45</em></button><button data-next-wave>Start next wave</button><ol data-defense-log><li>Place towers before starting a wave.</li></ol></aside></div></section>`;
  const canvas=$(stage,"[data-defense-canvas]"),ctx=canvas.getContext("2d");let towerType="edge";const sockets=[];for(let lane=0;lane<3;lane++)for(let col=0;col<5;col++)sockets.push({x:.2+col*.14,y:.23+lane*.27,lane,col});
  function draw(){const r=resizeCanvas(canvas),w=canvas.width,h=canvas.height;ctx.fillStyle="#071018";ctx.fillRect(0,0,w,h);for(let lane=0;lane<3;lane++){const y=(.23+lane*.27)*h;ctx.strokeStyle="rgba(113,229,255,.18)";ctx.lineWidth=28*r;ctx.beginPath();ctx.moveTo(0,y);ctx.lineTo(w,y);ctx.stroke();ctx.strokeStyle="rgba(113,229,255,.45)";ctx.lineWidth=2*r;ctx.stroke();}ctx.fillStyle="#ff7fa8";ctx.fillRect(w*.91,h*.08,w*.07,h*.78);ctx.fillStyle="#fff";ctx.font=`${14*r}px monospace`;ctx.save();ctx.translate(w*.945,h*.47);ctx.rotate(-Math.PI/2);ctx.textAlign="center";ctx.fillText("ORIGIN SERVER",0,0);ctx.restore();for(const s of sockets){const occupied=towers.find(t=>t.lane===s.lane&&t.col===s.col);ctx.strokeStyle=occupied?occupied.type==="edge"?"#71e5ff":"#ffd36e":"rgba(255,255,255,.16)";ctx.fillStyle=occupied?"rgba(113,229,255,.18)":"rgba(255,255,255,.025)";ctx.lineWidth=2*r;ctx.beginPath();ctx.arc(s.x*w,s.y*h,25*r,0,Math.PI*2);ctx.fill();ctx.stroke();if(occupied){ctx.fillStyle=occupied.type==="edge"?"#71e5ff":"#ffd36e";ctx.beginPath();ctx.arc(s.x*w,s.y*h,10*r,0,Math.PI*2);ctx.fill();}}for(const e of enemies){ctx.fillStyle=e.type==="heavy"?"#ff9a62":"#b68cff";ctx.fillRect(e.x*w-12*r,e.y*h-9*r,24*r,18*r);ctx.fillStyle="#fff";ctx.fillRect(e.x*w-12*r,e.y*h-15*r,24*r*(e.hp/e.maxHp),3*r);}for(const p of projectiles){ctx.fillStyle=p.color;ctx.beginPath();ctx.arc(p.x*w,p.y*h,4*r,0,Math.PI*2);ctx.fill();}}
  function updateUi(){$(stage,"[data-wave]").textContent=`${wave} / 6`;$(stage,"[data-credits]").textContent=Math.round(credits);$(stage,"[data-lives]").textContent=lives;$(stage,"[data-game-score]").textContent=score;}
  function loop(t){if(!running)return;const dt=Math.min(.03,(t-last)/1000||0);last=t;if(toSpawn>0){spawnTimer-=dt;if(spawnTimer<=0){const lane=Math.floor(Math.random()*3),heavy=wave>2&&Math.random()>.7;enemies.push({x:-.03,y:.23+lane*.27,lane,hp:heavy?90:45,maxHp:heavy?90:45,speed:heavy?.035:.06,type:heavy?"heavy":"normal"});toSpawn--;spawnTimer=.55;}}for(const e of enemies)e.x+=e.speed*dt;for(const tower of towers){tower.cool-=dt;if(tower.cool<=0){const target=enemies.find(e=>e.lane===tower.lane&&e.x>tower.x&&e.x-tower.x<(tower.type==="edge"?.23:.32));if(target){projectiles.push({x:tower.x,y:tower.y,target,damage:tower.type==="edge"?18:35,speed:.55,color:tower.type==="edge"?"#71e5ff":"#ffd36e"});tower.cool=tower.type==="edge"?.35:.8;}}}for(const p of projectiles){const dx=p.target.x-p.x,dy=p.target.y-p.y,d=Math.hypot(dx,dy);p.x+=dx/d*p.speed*dt;p.y+=dy/d*p.speed*dt;if(d<.02){p.target.hp-=p.damage;p.hit=true;}}projectiles=projectiles.filter(p=>!p.hit&&p.target.hp>0);for(const e of enemies){if(e.hp<=0){score+=10;credits+=8;}if(e.x>.91){lives--;e.hp=0;}}enemies=enemies.filter(e=>e.hp>0&&e.x<=.91);if(lives<=0){running=false;end(false);}else if(wave===6&&toSpawn===0&&!enemies.length){running=false;end(true);}draw();updateUi();frame=requestAnimationFrame(loop);}
  function startWave(){if(!running||toSpawn>0||enemies.length||wave>=6)return;wave++;toSpawn=5+wave*2;spawnTimer=0;$(stage,"[data-game-status]").textContent=`WAVE ${wave}`;$(stage,"[data-defense-log]").insertAdjacentHTML("afterbegin",`<li>Wave ${wave} incoming.</li>`);}
  function end(win){$(stage,"[data-game-status]").textContent=win?"DEFENDED":"OVERLOADED";const o=$(stage,"[data-game-overlay]");o.hidden=false;o.querySelector("strong").textContent=win?"ORIGIN SECURED":"ORIGIN OVERLOADED";o.querySelector("p").textContent=`Final score ${score}.`;o.querySelector("button").textContent="PLAY AGAIN";}
  canvas.addEventListener("click",e=>{if(!running)return;const rect=canvas.getBoundingClientRect(),x=(e.clientX-rect.left)/rect.width,y=(e.clientY-rect.top)/rect.height;const s=sockets.reduce((a,b)=>Math.hypot(x-b.x,y-b.y)<Math.hypot(x-a.x,y-a.y)?b:a);if(Math.hypot(x-s.x,y-s.y)<.05&&!towers.some(t=>t.lane===s.lane&&t.col===s.col)){const cost=towerType==="edge"?30:45;if(credits>=cost){credits-=cost;towers.push({...s,type:towerType,cool:0});updateUi();}}});$$(stage,"[data-tower]").forEach(b=>b.addEventListener("click",()=>{towerType=b.dataset.tower;$$(stage,"[data-tower]").forEach(x=>x.classList.toggle("selected",x===b));}));$(stage,"[data-next-wave]").addEventListener("click",startWave);
  function start(){cancelAnimationFrame(frame);wave=0;credits=100;lives=10;score=0;enemies=[];towers=[];projectiles=[];toSpawn=0;running=true;$(stage,"[data-game-overlay]").hidden=true;$(stage,"[data-game-status]").textContent="BUILD PHASE";last=performance.now();draw();updateUi();frame=requestAnimationFrame(loop);}$$(stage,"[data-tower]")[0].classList.add("selected");$(stage,"[data-game-start]").addEventListener("click",start);draw();onReady?.({engineType:"TOWER DEFENSE ENGINE"});return ctl(stage,()=>cancelAnimationFrame(frame),start,()=>({fps:"60",meshes:enemies.length+towers.length+projectiles.length}));
}

function createEvolution({stage,onReady}){
  let frame,running=false,last=0,organisms=[],food=[],generation=1,births=0,deaths=0,history=[];
  stage.innerHTML=`<section class="demo-surface game-evolution"><header><div><span>ARTIFICIAL LIFE SANDBOX</span><h2>Digital Species Evolution</h2></div><div class="evo-stats"><span>GEN <strong data-generation>1</strong></span><span>POP <strong data-population>0</strong></span><span>BEST <strong data-fitness>0</strong></span><b data-game-status>READY</b></div></header><div class="evo-layout"><main><canvas data-evo-canvas></canvas>${overlay("Digital Species Evolution","Organisms inherit speed, vision, size, and color. Survival and reproduction determine which traits dominate later generations.")}</main><aside><h3>ENVIRONMENT</h3><label>Simulation speed <select data-evo-speed><option value="1">1×</option><option value="3">3×</option><option value="8">8×</option></select></label><label>Mutation rate <output data-mutation-out>8%</output><input data-mutation type="range" min="0" max="30" value="8"></label><button data-add-food>Add energy burst</button><button data-catastrophe>Environmental shift</button><div class="trait-card"><span>SELECTED ORGANISM</span><strong data-selected>Click an organism</strong><p data-traits>Traits will appear here.</p></div><canvas data-evo-chart></canvas><div hidden data-game-score>0</div></aside></div></section>`;
  const canvas=$(stage,"[data-evo-canvas]"),ctx=canvas.getContext("2d"),chart=$(stage,"[data-evo-chart]"),chartCtx=chart.getContext("2d"),mutation=$(stage,"[data-mutation]");mutation.addEventListener("input",()=>$(stage,"[data-mutation-out]").textContent=`${mutation.value}%`);
  function seed(){organisms=Array.from({length:28},()=>({x:Math.random(),y:Math.random(),vx:0,vy:0,energy:60+Math.random()*40,age:0,speed:.035+Math.random()*.045,vision:.08+Math.random()*.12,size:.006+Math.random()*.009,hue:110+Math.random()*180,gen:1,fitness:0}));food=Array.from({length:70},()=>({x:Math.random(),y:Math.random()}));generation=1;births=0;deaths=0;history=[];}
  function mutate(v,range){return Math.max(range[0],Math.min(range[1],v+(Math.random()-.5)*(Number(mutation.value)/100)*(range[1]-range[0])));}
  function step(dt){const speed=Number($(stage,"[data-evo-speed]").value);dt*=speed;for(const o of organisms){o.age+=dt;o.energy-=dt*(2+o.speed*22+o.size*45);let target=null,dist=Infinity;for(const f of food){const d=Math.hypot(f.x-o.x,f.y-o.y);if(d<dist&&d<o.vision){dist=d;target=f;}}if(target){o.vx+=(target.x-o.x)/(dist||1)*o.speed*dt;o.vy+=(target.y-o.y)/(dist||1)*o.speed*dt;}else{o.vx+=(Math.random()-.5)*o.speed*dt;o.vy+=(Math.random()-.5)*o.speed*dt;}const mag=Math.hypot(o.vx,o.vy)||1;if(mag>o.speed){o.vx=o.vx/mag*o.speed;o.vy=o.vy/mag*o.speed;}o.x=(o.x+o.vx*dt+1)%1;o.y=(o.y+o.vy*dt+1)%1;for(let i=food.length-1;i>=0;i--){if(Math.hypot(food[i].x-o.x,food[i].y-o.y)<o.size+.006){food.splice(i,1);o.energy+=28;o.fitness++;}}if(o.energy>145&&organisms.length<90){o.energy*=.52;organisms.push({...o,x:(o.x+.02)%1,y:(o.y+.02)%1,energy:o.energy,age:0,speed:mutate(o.speed,[.02,.1]),vision:mutate(o.vision,[.04,.28]),size:mutate(o.size,[.004,.022]),hue:mutate(o.hue,[0,360]),gen:o.gen+1,fitness:0});births++;generation=Math.max(generation,o.gen+1);}}deaths+=organisms.filter(o=>o.energy<=0||o.age>95).length;organisms=organisms.filter(o=>o.energy>0&&o.age<=95);while(food.length<75)food.push({x:Math.random(),y:Math.random()});history.push(organisms.length);if(history.length>120)history.shift();if(!organisms.length){running=false;end();}}
  function draw(){const r=resizeCanvas(canvas),w=canvas.width,h=canvas.height;ctx.fillStyle="#071812";ctx.fillRect(0,0,w,h);for(const f of food){ctx.fillStyle="#d8ff72";ctx.beginPath();ctx.arc(f.x*w,f.y*h,3*r,0,Math.PI*2);ctx.fill();}for(const o of organisms){ctx.fillStyle=`hsl(${o.hue} 75% 60%)`;ctx.beginPath();ctx.arc(o.x*w,o.y*h,o.size*Math.min(w,h)*1.3,0,Math.PI*2);ctx.fill();ctx.strokeStyle=`hsla(${o.hue} 90% 70% / .18)`;ctx.beginPath();ctx.arc(o.x*w,o.y*h,o.vision*Math.min(w,h),0,Math.PI*2);ctx.stroke();}chart.width=chart.clientWidth*devicePixelRatio;chart.height=120*devicePixelRatio;chartCtx.clearRect(0,0,chart.width,chart.height);chartCtx.beginPath();history.forEach((v,i)=>{const x=i/119*chart.width,y=chart.height-v/100*chart.height;i?chartCtx.lineTo(x,y):chartCtx.moveTo(x,y);});chartCtx.strokeStyle="#88f5a7";chartCtx.lineWidth=2*devicePixelRatio;chartCtx.stroke();$(stage,"[data-generation]").textContent=generation;$(stage,"[data-population]").textContent=organisms.length;$(stage,"[data-fitness]").textContent=Math.max(0,...organisms.map(o=>o.fitness));$(stage,"[data-game-score]").textContent=organisms.length;}
  function loop(t){if(!running)return;const dt=Math.min(.04,(t-last)/1000||0);last=t;step(dt);draw();frame=requestAnimationFrame(loop);}function end(){const o=$(stage,"[data-game-overlay]");o.hidden=false;o.querySelector("strong").textContent="POPULATION EXTINCT";o.querySelector("p").textContent=`Reached generation ${generation} with ${births} births.`;o.querySelector("button").textContent="RESEED";$(stage,"[data-game-status]").textContent="EXTINCT";}
  canvas.addEventListener("click",e=>{const rect=canvas.getBoundingClientRect(),x=(e.clientX-rect.left)/rect.width,y=(e.clientY-rect.top)/rect.height;const o=organisms.reduce((a,b)=>Math.hypot(x-b.x,y-b.y)<Math.hypot(x-a.x,y-a.y)?b:a,organisms[0]);if(o){$(stage,"[data-selected]").textContent=`Generation ${o.gen} organism`;$(stage,"[data-traits]").textContent=`Speed ${(o.speed*1000).toFixed(0)} • vision ${(o.vision*100).toFixed(0)} • size ${(o.size*1000).toFixed(0)} • energy ${o.energy.toFixed(0)}`;}});$(stage,"[data-add-food]").addEventListener("click",()=>{for(let i=0;i<35;i++)food.push({x:.35+Math.random()*.3,y:.35+Math.random()*.3});});$(stage,"[data-catastrophe]").addEventListener("click",()=>{food=food.slice(0,15);organisms.forEach(o=>o.energy*=.72);});function start(){cancelAnimationFrame(frame);seed();running=true;$(stage,"[data-game-overlay]").hidden=true;$(stage,"[data-game-status]").textContent="EVOLVING";last=performance.now();frame=requestAnimationFrame(loop);}$(stage,"[data-game-start]").addEventListener("click",start);seed();draw();onReady?.({engineType:"EVOLUTION SIMULATOR"});return ctl(stage,()=>cancelAnimationFrame(frame),start,()=>({fps:"60",meshes:organisms.length+food.length}));
}

function createLogistics({stage,onReady}){
  const cities=[{n:"Davis",x:.15,y:.55},{n:"Freeport",x:.34,y:.36},{n:"Rockford",x:.62,y:.48},{n:"Beloit",x:.45,y:.16},{n:"Madison",x:.7,y:.12},{n:"Chicago",x:.88,y:.7}];const roads=[[0,1],[1,2],[1,3],[3,4],[2,4],[2,5],[4,5]];
  let day=1,cash=8500,reputation=82,trucks=[],contracts=[],selectedTruck=null,selectedContract=null,frame,running=false,last=0;
  stage.innerHTML=`<section class="demo-surface game-logistics"><header><div><span>PCS LLC / REGIONAL DISPATCH</span><h2>Logistics Challenge</h2></div><div class="dispatch-stats"><span>DAY <strong data-day>1</strong></span><span>CASH <strong data-cash>$8,500</strong></span><span>REP <strong data-rep>82</strong></span><span>SCORE <strong data-game-score>0</strong></span><b data-game-status>READY</b></div></header><div class="logistics-layout"><aside class="fleet"><h3>FLEET</h3><div data-fleet></div><button data-maintenance>Run maintenance</button></aside><main><canvas data-logistics-canvas></canvas>${overlay("PCS Logistics Challenge","Select a truck and a contract, dispatch it across the regional road network, and keep fuel, deadlines, maintenance, cash, and reputation under control.")}</main><aside class="contracts"><h3>CONTRACT BOARD</h3><div data-contracts></div><button data-dispatch>Dispatch selected</button><button data-advance>Advance day</button><ol data-logistics-log><li>Dispatch office ready.</li></ol></aside></div></section>`;
  const canvas=$(stage,"[data-logistics-canvas]"),ctx=canvas.getContext("2d");function seed(){trucks=[{id:1,name:"Truck 12",city:0,fuel:100,health:92,capacity:8,status:"available",route:null,progress:0},{id:2,name:"Truck 18",city:1,fuel:84,health:78,capacity:12,status:"available",route:null,progress:0},{id:3,name:"Truck 21",city:2,fuel:65,health:88,capacity:10,status:"available",route:null,progress:0}];contracts=[{id:1,from:1,to:2,load:7,pay:1300,days:2},{id:2,from:0,to:4,load:9,pay:2200,days:3},{id:3,from:2,to:5,load:11,pay:2600,days:2},{id:4,from:3,to:1,load:5,pay:950,days:1}];day=1;cash=8500;reputation=82;selectedTruck=null;selectedContract=null;}
  function renderPanels(){$(stage,"[data-fleet]").innerHTML=trucks.map(t=>`<button data-truck="${t.id}" class="${selectedTruck===t.id?"selected":""} ${t.status}"><span><strong>${t.name}</strong><small>${cities[t.city].n} • ${t.capacity} ton</small></span><em>${t.status}</em><meter min="0" max="100" value="${t.fuel}"></meter><b>${Math.round(t.fuel)}% fuel</b></button>`).join("");$(stage,"[data-contracts]").innerHTML=contracts.map(c=>`<button data-contract="${c.id}" class="${selectedContract===c.id?"selected":""}"><span><strong>${cities[c.from].n} → ${cities[c.to].n}</strong><small>${c.load} tons • due ${c.days}d</small></span><em>$${c.pay}</em></button>`).join("");$$(stage,"[data-truck]").forEach(b=>b.addEventListener("click",()=>{selectedTruck=Number(b.dataset.truck);renderPanels();}));$$(stage,"[data-contract]").forEach(b=>b.addEventListener("click",()=>{selectedContract=Number(b.dataset.contract);renderPanels();}));$(stage,"[data-day]").textContent=day;$(stage,"[data-cash]").textContent=`$${Math.round(cash).toLocaleString()}`;$(stage,"[data-rep]").textContent=Math.round(reputation);$(stage,"[data-game-score]").textContent=Math.round(cash+reputation*100);}
  function draw(){const r=resizeCanvas(canvas),w=canvas.width,h=canvas.height;ctx.fillStyle="#18231d";ctx.fillRect(0,0,w,h);ctx.fillStyle="#213a2c";for(let i=0;i<18;i++){ctx.beginPath();ctx.arc((i*197%w),(i*113%h),50*r,0,Math.PI*2);ctx.fill();}for(const [a,b] of roads){ctx.strokeStyle="#c7b18b";ctx.lineWidth=10*r;ctx.beginPath();ctx.moveTo(cities[a].x*w,cities[a].y*h);ctx.lineTo(cities[b].x*w,cities[b].y*h);ctx.stroke();ctx.strokeStyle="#f5e6c5";ctx.lineWidth=2*r;ctx.setLineDash([8*r,10*r]);ctx.stroke();ctx.setLineDash([]);}for(const c of cities){ctx.fillStyle="#ff9a62";ctx.beginPath();ctx.arc(c.x*w,c.y*h,10*r,0,Math.PI*2);ctx.fill();ctx.fillStyle="#fff";ctx.font=`${14*r}px sans-serif`;ctx.fillText(c.n,c.x*w+15*r,c.y*h-12*r);}for(const t of trucks){let x=cities[t.city].x,y=cities[t.city].y;if(t.route){const a=cities[t.route.from],b=cities[t.route.to];x=a.x+(b.x-a.x)*t.progress;y=a.y+(b.y-a.y)*t.progress;}ctx.fillStyle=t.status==="available"?"#71e5ff":"#ffd36e";ctx.fillRect(x*w-12*r,y*h-8*r,24*r,16*r);ctx.fillStyle="#071019";ctx.fillRect(x*w+5*r,y*h-4*r,8*r,8*r);}}
  function dispatch(){const t=trucks.find(x=>x.id===selectedTruck),c=contracts.find(x=>x.id===selectedContract);if(!t||!c||t.status!=="available"||t.capacity<c.load)return;if(t.city!==c.from){$(stage,"[data-logistics-log]").insertAdjacentHTML("afterbegin","<li>Truck is not at the contract origin.</li>");return;}t.status="en route";t.route={...c};t.progress=0;contracts=contracts.filter(x=>x.id!==c.id);selectedContract=null;$(stage,"[data-logistics-log]").insertAdjacentHTML("afterbegin",`<li>${t.name} dispatched to ${cities[c.to].n}.</li>`);renderPanels();}
  function advance(){day++;for(const c of contracts)c.days--;for(const c of contracts.filter(c=>c.days<0)){reputation-=6;$(stage,"[data-logistics-log]").insertAdjacentHTML("afterbegin",`<li>Missed ${cities[c.from].n} contract deadline.</li>`);}contracts=contracts.filter(c=>c.days>=0);for(const t of trucks){if(t.route){t.progress+=.5;t.fuel-=14;t.health-=2;if(t.progress>=1){t.city=t.route.to;t.status="available";cash+=t.route.pay;reputation+=2;$(stage,"[data-logistics-log]").insertAdjacentHTML("afterbegin",`<li>${t.name} completed delivery for $${t.route.pay}.</li>`);t.route=null;t.progress=0;}}}if(day%2===0){const from=Math.floor(Math.random()*5),to=(from+1+Math.floor(Math.random()*5))%6;contracts.push({id:Date.now(),from,to,load:4+Math.floor(Math.random()*8),pay:900+Math.floor(Math.random()*1800),days:1+Math.floor(Math.random()*3)});}renderPanels();draw();if(reputation<=40||day>14)end();}
  function end(){running=false;$(stage,"[data-game-status]").textContent=reputation<=40?"CONTRACT LOST":"TWO WEEKS COMPLETE";const o=$(stage,"[data-game-overlay]");o.hidden=false;o.querySelector("strong").textContent=reputation<=40?"REPUTATION COLLAPSED":"DISPATCH PERIOD COMPLETE";o.querySelector("p").textContent=`Cash $${Math.round(cash).toLocaleString()} • reputation ${Math.round(reputation)}.`;o.querySelector("button").textContent="PLAY AGAIN";}
  $(stage,"[data-dispatch]").addEventListener("click",dispatch);$(stage,"[data-advance]").addEventListener("click",advance);$(stage,"[data-maintenance]").addEventListener("click",()=>{const t=trucks.find(x=>x.id===selectedTruck);if(t&&cash>=500&&t.status==="available"){cash-=500;t.health=100;t.fuel=100;renderPanels();}});function start(){seed();running=true;$(stage,"[data-game-overlay]").hidden=true;$(stage,"[data-game-status]").textContent="DISPATCHING";renderPanels();draw();}$(stage,"[data-game-start]").addEventListener("click",start);seed();renderPanels();draw();onReady?.({engineType:"ROUTE MANAGEMENT ENGINE"});return ctl(stage,undefined,start,()=>({fps:"60",meshes:trucks.length+contracts.length}));
}

const creators={"cloud-ops-crisis":createCloudOps,"golf-challenge":createGolf,"code-dungeon":createDungeon,"data-center-defense":createDefense,"digital-evolution":createEvolution,"pcs-logistics":createLogistics};
export function createBrowserGame(context){const create=creators[context.demo.id];if(!create)throw new Error(`Unknown game: ${context.demo.id}`);return create(context);}
